### ISSUE TITLE
log_called_apiテーブルのレコードは削除しても問題ないか

### ISSUE THREAD

**Issue by jou-imaizumi** [Personal-Data-Linkage-Module/pxr-linkage#102]
表題の件について、確認を行いたいです。

現在DBの容量が想定よりも多く使用されており、詳細を調べたところ以下のテーブルの使用容量が他と比較して多いことが判明いたしました。
このテーブルのレコードを削除してもサービスに影響がないかご教授お願いいたします。

【対象テーブル】
対象DB：root,region,app
対象スキーマ：pxr_block_proxy
対象テーブル：log_called_api

**Comment by r-saito-cw** [comment]
問い合わせに回答します。
log_called_apiのデータを削除しても動作には問題ありません。
よろしくお願いします。
