### ISSUE TITLE
ユーザが多い状態だと、region-cooperate-region-batchが正常に動作しない 

### ISSUE THREAD

**Issue by jou-imaizumi** [Personal-Data-Linkage-Module/pxr-linkage#103]
性能の検証用に10000人程のユーザを作成し、検証を行っています。
region-cooperate-region-batchを5分に一度実行しながら、10000人のユーザのRegion連係を行いました。
その結果、8000人のユーザを作成したあたりから、region-cooperate-region-batchでエラーになってしまい。連携ができませんでした。
登録しているユーザが多い状態だと、region-cooperate-region-batch内部の処理(承認要求通知リスト取得)の箇所でエラーになるようでした。
以下に詳細を記載するので、ご確認よろしくお願いします。

## region-cooperate-region-batchのログ
[region_cooperation_batch.log](https://github.com/user-attachments/files/16159369/region_cooperation_batch.log)

#### リクエスト
・実行ユーザ：regionのtype3ユーザ

```
curl -v -k -X GET \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-H 'x-xsrf-token:GrvGcs4O-Xyc54Rqdyhd1BdbZuy1MbyZnvgU' \
-b 'operator_type0_session=47e7c9871a287a0a7b9f513426a1440f149c33eb2748171502c9a3521a808137;_csrf=o4mGlnsOFDWWraWC0RmP2yNW' \
'https://{regionのホスト名}/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=1000783&path=%2Fnotification%2F%3Fis_send%3Dfalse%26is_unread%3Dtrue%26is_approval%3Dfalse%26type%3D0%26num%3D1'
```

#### レスポンス
```
[
    {
        "id": 16812,
        "type": 0,
        "title": "連携用本人性確認コード発行",
        "content": "個人から利用者ID連携の連携要求がきました",
        "attribute": {
            "identifyCode": "NDUxNTg0MzQtMzliNi00OWFmLTliNDAtYzdkOTliOWEyZjVj",
            "verifiedFlg": false
        },
        "category": {
            "_value": 145,
            "_ver": 1
        },
        "from": {
            "blockCode": 1000401,
            "operatorId": 9947,
            "actor": {
                "_value": 1000431,
                "_ver": 1
            }
        },
        "readAt": null,
        "sendAt": "2024-07-10T19:21:39.873+0900",
        "is_transfer": false
    }
]
```

#### リクエスト
・実行ユーザ：regionのtype3ユーザ
```
curl -v -k -X GET \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-H 'x-xsrf-token:GrvGcs4O-Xyc54Rqdyhd1BdbZuy1MbyZnvgU' \
-b 'operator_type0_session=47e7c9871a287a0a7b9f513426a1440f149c33eb2748171502c9a3521a808137;_csrf=o4mGlnsOFDWWraWC0RmP2yNW' \
'https://{regionのホスト名}/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=1000783&path=%2Fnotification%2F%3Fis_send%3Dfalse%26is_unread%3Dtrue%26is_approval%3Dfalse%26type%3D0%26num%3D0'
```

#### レスポンス
```
{
    "status": 500,
    "message": "宛先ブロックのリバースプロキシーAPIの呼び出しに失敗しました"
}
```

**Comment by jou-imaizumi** [comment]
※追記
バッチのmanifestで以下の変更を行うと正常に動作しているように見えるのですが、問題はないでしょうか？？

【修正内容】
承認要求通知リストを全件取得から、1000件取得に変更
※クエリの「num」の値を0→1000に変更

【変更箇所】
対象ファイル：cooperate-region-batch-container.yaml
対象箇所：config.jsonの中の、notificationService.getNotificationの値
修正前：
`https://region-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block={regionのblockコード}&path=%2Fnotification%2F%3Fis_send%3Dfalse%26is_unread%3Dtrue%26is_approval%3Dfalse%26type%3D0%26num%3D0`

修正後：
`https://region-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block={regionのblockコード}&path=%2Fnotification%2F%3Fis_send%3Dfalse%26is_unread%3Dtrue%26is_approval%3Dfalse%26type%3D0%26num%3D1000`

**Comment by r-saito-cw** [comment]
追加情報を得ましたので投稿します。これにてCLOSEします。

numがゼロの場合は未読の通知を全件取得してしまっているため、manifestで1000件を指定する修正で問題ないです。
処理が終わった通知に関しては既読処理が行われるため再処理される事はありません。
