### ISSUE TITLE
カタログ作成APIの "base-url" と "first-login-url" に設定する値の情報が不足している

### ISSUE THREAD

**Issue by kizumitani** [Personal-Data-Linkage-Module/pxr-linkage#12]
パーソナルデータ連携モジュール_利用設定手順書_v1.1 p14 に記載の "カタログ作成 API" の "base-url" と "first-login-url" のフィールドについて、下記のように説明の記載がありますが具体的にはどこの処理で使われる値なのかご教示頂けないでしょうか。
(お客様にヒアリングを行い、決める必要のある値なのかどうかを判断したいと思っております)

ポータルの URL : 対象のアクター用ポータルのベース URL を設定する。 例）https://[base-url]/portal/login
ポータルの初回ログイン URL : PxR-Block 以外は null が設定される

**Comment by ToshinoriOchiai** [comment]
本モジュールの機能範囲では利用いたしません。

ドキュメント記載のポータルとは、サービス事業者向けのポータルサイトを指しております。
パーソナルデータ連携モジュールにはUI機能はなく、各基盤事業者様でご用意頂くため、設定値は利用されません。
