### ISSUE TITLE
Region改定再同意依頼バッチに関する質問

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#18]
# 状況
以前のセミナーでいただいたバッチについて調査しているのですが、いくつか質問事項が発生しました。
内容についてご教授いただけないでしょうか。

# 質問事項
## Region改定再同意依頼バッチ
1. PxR側の実装を見ると、規約がPF利用規約の場合の分岐も存在するようです。
  例えば、pxr-book-manageのTermsOfUseService.ts#getTermsOfUseTargetFind() の処理で分岐が存在します。
  本バッチでPF利用規約更新時の再同意依頼処理もまかなえる理解でよろしいでしょうか。
  または、PF利用規約用のバッチ開発が必要となるのでしょうか。
2. バッチとは異なるかもしれませんが、規約更新時に個人に規約再同意を促すフローはあるのでしょうか。
    メール or SMSで通知するフローを想定しておりますが、実装が必要となる場合、どの部分になりますでしょうか。
　＃モジュールとしてSMSでの通知前提ではありますが、SMSではなくメールで代用可能かも併せて確認させてください。

**Comment by k-inoue** [comment]
１．について
本バッチ（region-term-of-use-notification-batch）はRegion用になりますので、
Platformの利用規約に関する処理には対応しておりません。
よって、ご推察のとおり、PF利用規約用のバッチ開発が必要となります。
参考までにPF利用規約に関するバッチサンプルをご提供いたしますので、
ご確認いただき、作成をお願いいたします。

２．について
規約更新の通知に関してですが、①のバッチを参考にご説明すると
規約更新後、バッチにて通知サービスに更新情報が格納されますので、
通知サービス用のAPI「/notification/（GET）」を利用して情報を取得する部分以降の実装が必要となります。
＃メールやSNS等への送信も含め

APIにつきましては、公開しておりますAPIリストをご確認ください。
ファイル名：パーソナルデータ連携モジュール_公開APIリスト_v1.0.pdf
[pxr-platform-term-of-use-notification-batch.zip](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/12239323/pxr-platform-term-of-use-notification-batch.zip)

**Comment by k-inoue** [comment]
バッチに関するmanifestファイルを添付いたします。
[manifest.zip](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/12256435/manifest.zip)
