### ISSUE TITLE
pxr_book_manage.temporarily_shared_codeテーブルの作成に失敗する

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#26]
# 状況
createTable.sqlのCREATE TABLEを実行して、pxr_book_manage.temporarily_shared_codeを作成すると
以下のエラーにより失敗します。
```
ERROR: function uuid_generate_v4() does not exist
```

CREATE EXTENSIONの実行手順がドキュメントに書かれていないと推察しております。
`パーソナルデータ連携モジュール_構築ガイド` の「2.3 DB構築」に記載するのがいいと考えておりますがいかがでしょうか。
修正をお願いいたします。

また、手順について、以下で認識合いますでしょうか。
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```

**Comment by ToshinoriOchiai** [comment]
現在、公開されている「pxr-book-manage-service\createTable.sql」には、ご指摘頂いた内容が反映されております。

https://github.com/Personal-Data-Linkage-Module/pxr-linkage/blob/main/database/pxr-book-manage-service/createTable.sql
