### ISSUE TITLE
利用規約同意後の同意撤回機能について

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#27]
# 確認事項
PF利用規約およびRegion利用規約に同意後、同意を撤回する機能について調査しております。
機能要件テンプレートやAPIを確認しておりますが同意を撤回するような機能は存在しないのでしょうか。

存在しない場合、追加実装が必要となりますでしょうか。
その際、どのように実装を行えばよいかご教授いただけないでしょうか。

**Comment by ToshinoriOchiai** [comment]
「利用規約の同意を撤回」とは「利用を解除」と同義です。下記をご覧ください。

機能要件テンプレート_本紙_v1.1.xlsx　[A-b-3-9_UX一覧]シート
・Region利用規約の同意撤回
　→フロー番号：4「個人がサービス（Region）の利用を終了する」
・PF利用規約の同意撤回
　→フロー番号：7「個人がプラットフォームの利用を終了する」

＜機能要件テンプレート_本紙_v1.1.xlsx＞
https://github.com/Personal-Data-Linkage-Module/pxr-linkage/blob/main/doc/%E6%A9%9F%E8%83%BD%E8%A6%81%E4%BB%B6%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88/%E6%A9%9F%E8%83%BD%E8%A6%81%E4%BB%B6%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88/%E6%A9%9F%E8%83%BD%E8%A6%81%E4%BB%B6%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88_%E6%9C%AC%E7%B4%99_v1.1.xlsx

**Comment by tomo-nagae** [comment]
回答ありがとうございます。

この回答通りとすると、以下の内容はどのようになりますでしょうか。
①
機能要件テンプレートを確認しましたが、テンプレートに記載されている処理名とAPI名が一致していないため、
どのAPIを使えばいいかわかりません。
具体的にどのAPIを使えてばよいかご教授いただけないでしょうか。

②
Region利用規約の同意撤回が「個人がサービス（Region）の利用を終了する」と同義、
PF利用規約の同意撤回が「個人がプラットフォームの利用を終了する」と同義とありますが、
引き続き個人がサービスを利用したい場合、再同意は可能なのでしょうか。
その場合、ログインして、未同意規約を取得して、同意するフローとなりますでしょうか。

③
上記の利用終了時、蓄積データ等は物理削除されるのでしょうか。または論理削除なのでしょうか。
②の通り再同意した状態で同意撤回前のデータは残っており、共有等で利用できるのか確認させてください。

**Comment by k-inoue** [comment]
本件確認中ですが、①について回答を記載いたします。

★Region利用規約の同意撤回（Region自動終了）

　個人でログインし以下のAPI実施
　POST https:///pxr-block-proxy/pxr-block-proxy/?block=$pxr-root-block&path=/book-manage/output/condition/prepare

　リクエスト内容イメージ
```json
{
"type": 3,
"actor": {
"_value": actorCode,
"_ver": actorVer
},
"region": {
"_value": regionCode,
"_ver": regionVer
},
"cooperationRelease": true
}

- 出力タイプ：3（Region利用自動終了）
- アクターコード：利用終了Regionのアクターコード※１
- Regionコード：利用終了Regionコード※１
- 利用者連携解除フラグ：true
　※１：Region利用規約の同意解除対象となるRegionの情報を設定する様に実装する事が必要となります

　上記の設定を実施し、サンプルで提供しているバッチ処理にて連携済みのRegion利用が終了します。

★PF利用規約の同意撤回（BOOK閉鎖）

　個人でログインし以下のAPI実施
　POST https:///pxr-block-proxy/pxr-block-proxy/?block=$pxr-root-block&path=/book-manage/output/condition/prepare

　リクエスト内容イメージ
```json
{
"type": 4,
"cooperationRelease": false
}

- 出力タイプ：4（Book閉鎖）
- 利用者連携解除フラグ：false  
　上記の設定を実施する事で、サンプルで提供しているバッチ動作にてBOOK閉鎖します。

**Comment by tomo-nagae** [comment]
## 追加確認
上記の回答で記載いただいているバッチですが、以下の認識でよろしいでしょうか。
■Region利用規約の同意撤回（Region自動終了）
　⇒Region利用自動終了バッチ
　※Region-Root-Blockで実行
■ PF利用規約の同意撤回（BOOK閉鎖）
　⇒利用者データ削除バッチ
　⇒Book削除バッチ
　※全PxR-Blockで実行
　以下のissueで確認いただいているフローと同じ認識です。
　https://github.com/Personal-Data-Linkage-Module/pxr-linkage/issues/51

**Comment by k-inoue** [comment]
①については以下ですでに回答済みではありますが、再掲含め回答いたします。
https://github.com/Personal-Data-Linkage-Module/pxr-linkage/issues/27#issuecomment-1665065426

①Region利用終了およびPF利用終了に関するAPIについて
★Region利用規約の同意撤回（Region自動終了）

　個人でログインし以下のAPI実施
　POST https:///pxr-block-proxy/pxr-block-proxy/?block=$pxr-root-block&path=/book-manage/output/condition/prepare

　リクエスト内容イメージ
json

~~~
{
	"type": 3,
	"actor": {
		"_value": actorCode,
		"_ver": actorVer
	},
	"region": {
		"_value": regionCode,
		"_ver": regionVer
	},
	"cooperationRelease": true
}
~~~
出力タイプ：3（Region利用自動終了）
アクターコード：利用終了Regionのアクターコード※１
Regionコード：利用終了Regionコード※１
利用者連携解除フラグ：true
　※１：上記サンプルのactorCode、regionCodeには同意解除対象となるRegionの情報を設定してください。
　上記の設定を実施し、サンプルで提供しているバッチ処理にて連携済みのRegion利用が終了します。

★PF利用規約の同意撤回（BOOK閉鎖）

　個人でログインし以下のAPI実施
　POST https:///pxr-block-proxy/pxr-block-proxy/?block=$pxr-root-block&path=/book-manage/output/condition/prepare

　リクエスト内容イメージ
json

~~~
{
	"type": 4,
	"cooperationRelease": false
}
~~~
出力タイプ：4（Book閉鎖）
利用者連携解除フラグ：false
　上記の設定を実施する事で、サンプルで提供しているバッチ動作にてBOOK閉鎖します。


②規約同意撤回後の再同意について
　結論からですが、利用規約撤回前のデータを対象とした再同意はできない仕様となっております。
　利用終了により、利用者ID連携も解除されます。
　利用者ID 連携解除後、同じアプリケーション内で同じ個人に利用者 ID が再連携されるのか／別の個人に利用者 ID が再連携されるのかを
　判別をする機能はないため、安全のためにガードする実装となっております。
　よって、利用規約の同意撤回後は、新規同意という形の流れとなります。

③蓄積データ物理削除について
　蓄積データを物理削除するかどうか？については、デフォルトでは論理削除となります。
　ただし、利用規約内に物理削除フラグがあり、このフラグの設定次第で物理削除も可能です。
　②の回答通り、同一個人データでの利用規約再同意はできませんので、共有等での利用もできません。


合わせて、①の回答に対して追加でいただいたバッチに関するご質問にも回答いたします。

■Region利用規約の同意撤回（Region自動終了）
　⇒Region利用自動終了バッチ
　※Region-Root-Blockで実行
■ PF利用規約の同意撤回（BOOK閉鎖）
　⇒利用者データ削除バッチ
　⇒Book削除バッチ
　※全PxR-Blockで実行

はい、上記で認識あっておりますが、両者実行前に以下の実行が必要となることと、
利用終了に関連するissueが発行されておりますので、要件に応じてこのissueの状況についてもご確認ください。
・データ出力準備APIの実行
・出力データファイル管理作成バッチ（output user data file mng batch）

★関連するissue
https://github.com/Personal-Data-Linkage-Module/pxr-linkage/issues/74


上記内容にてCloseしてよろしければ、その旨を返信願います。
１週間経過後にお返事いただけていない場合は、CLOSEいたします。
Reopenご希望の場合は、返信いただくかコミュニティのSlackにてメンションいただけますようお願いします

**Comment by ToshinoriOchiai** [comment]
１週間以上経過しましたので、Close致します。
Close後にもReopenは可能ですので、Slack等でご連絡ください。
