### ISSUE TITLE
蓄積同意の撤回機能について

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#28]
# 確認事項
蓄積同意後、同意を撤回する機能について調査しております。

以下の方法で蓄積同意の状態を撤回することができると考えておりますが認識合いますでしょうか。

1.  データ蓄積定義取得：「GET /book-manage/settings/store/{id}」
　⇒同意済のデータ蓄積定義を取得

1. storeCatalogId取得：「GET /catalog/{code}」
　⇒「1.」で取得したコードを指定してstoreCatalogIdを取得

1. storeCatalogIdから蓄積を定義しているカタログを取得する？：「GET /catalog/{code}」
　⇒蓄積データの詳細情報を取得？

1. データ蓄積定義削除：「DELETE /book-manage/settings/store/{storeId}」
　⇒「2.」「3.」で取得したstoreIdを指定してデータ蓄積定義を削除

また、共有同意についても類似のAPIが存在しておりますので、同様に同意を撤回できる認識でよろしいでしょうか。

**Comment by k-inoue** [comment]
蓄積同意の取り消し手順について回答いたします。
ご記入いただいた手順の１および４の実施で蓄積同意の取り消しを行うことができます

■蓄積同意の取り消し
①データ蓄積定義取得：「GET /book-manage/settings/store/{id}」を実行
　→idには利用者IDを指定
　→API実行後のレスポンスデータ内にあるidが②で利用するstoreIdになります。
②データ蓄積定義削除：「DELETE /book-manage/settings/store/{storeId}」を実行

また、共有同意の取り消しについてですが、こちらは以下となります。
■共有同意の取り消し
①データ共有定義取得：「GET /book-manage/settings/share」を実行
　クエリパラメータとしてapp={app_code}を利用。
　例：/book-manage/settings/share?app={app_code}
　→app_codeは共有同意解除予定のアプリケーションのコードを指定
　→API実行後のレスポンスデータ内にあるidが②で利用するshareIdになります。

②データ共有定義削除：「DELETE /book-manage/settings/share/{shareId}」を実行

なお、参考情報となりますが、蓄積同意処理に関連する以下のissueが発行されております。
対応に向け、コミュニティ内にて検討を進めてまいります。ご了承ください。
■削除済の蓄積定義と同じ個人、蓄積定義カタログの組み合わせで再度蓄積定義追加ができない
https://github.com/Personal-Data-Linkage-Module/pxr-linkage/issues/61

上記内容にてCloseしてよろしければ、その旨を返信願います。
１週間経過後にお返事いただけていない場合は、CLOSEいたします。
Reopenご希望の場合は、返信いただくかコミュニティのSlackにてメンションいただけますようお願いします

**Comment by ToshinoriOchiai** [comment]
1週間以上経過したため、クローズさせて頂きます。何かあれば、Slac等でkご連絡ください。
引き続き、宜しくお願い致します。
