### ISSUE TITLE
個人でのMy-Condition-Bookの開設実現可否について

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#29]
# 前提
不特定多数の住民が機能要件テンプレートのような自治体向けのサービスを利用するためにBook開設をする想定です。
その際、流通制御SPの運営メンバアカウントが不特定多数（大人数）のアカウントを手動で発行することは現実的ではないと考えております。
そのため、質問票で質問させていただき以下の回答を受領しております。
■質問票での質問内容
```
PxRの個人アカウントの作成 (My-Condition-Book の開設) はすべて流通制御SPが実施し、個人でのサインアップはできない想定でしょうか？
もし、個人でアカウントの作成を実施させたい場合、追加実装を行う必要がありますか？ 
(追加実装が必要な場合はどのように実装を行えばよいかもご教示頂きたいです。)
```
■質問票での回答内容
```
ご認識のとおり、基本的にすべて流通制御SPで実施を想定しております。
> もし、個人でアカウントの作成を実施させたい場合、追加実装を行う必要がありますか？ 
> (追加実装が必要な場合はどのように実装を行えばよいかもご教示頂きたいです。)
追加実装が必要となります。
OSS版としては想定していない内容となりますので、具体的な方法については
book開設の実装を参考にしていただき、ご検討いただければ幸いです。
```

# 確認事項
個人でBook開設する方法を検討しましたが、Book開設前のためログインできないと考えております。
このため、個人でのBook開設の実現はは難しいと考えております。
この場合の、不特定多数の住民のBook開設を実施するためのベストプラクティスについてご教授いただけないでしょうか。
＃ちなみに、ポータル画面にサインアップ画面を作る場合、アクセスしてきた住民(個人)がBook開設する方法はあるのでしょうか。

**Comment by ToshinoriOchiai** [comment]
流通制御SP運営メンバーにてBook開設APIを呼び出すことでBook開設が可能です。
ただし、個人のBook開設にあたり、本人確認を実施する必要があります。
そのため、例えば、外部の個人認証サービスでの本人確認に基づきAPIを呼び出す処理を実装頂ければ、
自動化することが可能です。

なお、コミュニティでは、外部個人認証サービスとの連携処理をプラグイン化する機能として
「マイナンバーカード認証連携機能」を現在検討中です。
