### ISSUE TITLE
個人への通知手段

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#30]
# 確認事項
個人に通知する機能としてSMSがスタブとして提供されている認識ですが、メールでの代用は可能でしょうか。

**Comment by k-inoue** [comment]
SMS用のスタブ利用は必須ではありません。
ご質問いただいたメールの利用も事業者様にて実装のうえ、実現をお願いいたします。

個人への通知としては以下ございますが、ともにSMSでの通知を想定しておりまますので、メールを利用される場合はメールアドレスの取得含め、実装をお願いいたします。
・二段階認証におけるSMS検証コード発行（POST /operator/ind/sms-verificate）
・Book開設時のガイダンス送信(POST /book-manage/sms/open)

上記内容にてCloseしてよろしければ、その旨を返信願います。
１週間経過後にお返事いただけていない場合は、CLOSEいたします。
Reopenご希望の場合は、返信いただくかコミュニティのSlackにてメンションいただけますようお願いします

**Comment by k-inoue** [comment]
SMS用のスタブ利用は必須ではありません。
ご質問いただいたメールの利用も事業者様にて実装のうえ、実現をお願いいたします。

個人への通知としては以下ございますが、ともにSMSでの通知を想定しておりまますので、
メールを利用される場合はメールアドレスの取得含め、実装をお願いいたします。
・二段階認証におけるSMS検証コード発行（POST /operator/ind/sms-verificate）
・Book開設時のガイダンス送信(POST /book-manage/sms/open)

上記内容にてCloseしてよろしければ、その旨を返信願います。
１週間経過後にお返事いただけていない場合は、CLOSEいたします。
Reopenご希望の場合は、返信いただくかコミュニティのSlackにてメンションいただけますようお願いします

**Comment by ToshinoriOchiai** [comment]
1週間以上経過したため、クローズさせて頂きます。何かあれば、Slack等でご連絡ください。
引き続き、宜しくお願い致します。
