### ISSUE TITLE
アプリケーションとの利用者ID連携方法について

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#32]
# 確認事項
アプリケーションとの利用者ID連携をSlackで共有いただいた以下の方法で実現する場合、
③の画面でコードを入力した場合、どのようなフローで利用者ID連携が完了するのでしょうか。
Book管理サービスの利用者ID連携APIを実行するのでしょうか。
その場合、リクエストに設定する値はどのようになりますでしょうか。
・identifyCode：①で発行されるコード（これが画面上から入力される）
・path：アプリケーションPで実行して取得する必要がありますでしょうか。

【アプリケーションとの利用者ID連携】
参考：https://cfj.slack.com/archives/C04GCMCFL21/p1683795596083219?thread_ts=1683771222.670799&cid=C04GCMCFL21
```
①住民ポータルで対象アプリを選択して、コード発行
　　※ここで⑤の蓄積同意と共有同意も可能
　　※但し、利用者ID連携完了まで蓄積、共有は行えない
②サービスアプリで何らかのメニュー（例えば、データ連携オプション
　メニュー）から住民ポータル（利用者ID連携画面）にリダイレクト
③利用者ID連携画面でコード入力
　　※利用者ID連携が完了し、蓄積および共有が可能になる
④サービスアプリに戻るとデータ連携オプションが有効になっている
利用者ID連携画面についても、セミナーで説明予定ですが、
ざっくり言うと
　・住民ポータルの一部だが、認証を必要とせず、本人性確認コードで
　　対応する利用者ID連携を完了させるだけの画面
です。
```

**Comment by k-inoue** [comment]
> ③の画面でコードを入力した場合、どのようなフローで利用者ID連携が完了するのでしょうか。
> Book管理サービスの利用者ID連携APIを実行するのでしょうか。

ご推察のとおり、利用者ID連携API(cooperate)を実行します。
利用者ID連携の流れについては、公開しております接続事業者向けセミナー資料にも記載しておりますので
ご確認ください。
・パーソナルデータ連携モジュール_セミナー資料（接続事業者様向け）.pdf
　→スライド39～41
・接続事業者向けセミナー_STEP2-2手順詳細.xlsx
　→シート「S22-1-2」～「S22-1-7」



> その場合、リクエストに設定する値はどのようになりますでしょうか。
> ・identifyCode：①で発行されるコード（これが画面上から入力される）
> ・path：アプリケーションPで実行して取得する必要がありますでしょうか。

identifyCodeについては、上記、手順詳細の資料ですと、シート「S22-1-2」を実行した応答データとして返却される値となります。
pathについては、アプリケーションPにてシート「S22-1-4」のAPIを実行して取得する必要があります。

利用者ID連携から蓄積/共有を開始するまでのフローはアプリケーション構築ガイドにも記載しておりますので、
こちらも合わせてご確認ください。
doc/利用ガイドライン/パーソナルデータ連携モジュール_アプリケーション開発ガイド/パーソナルデータ連携モジュール_アプリケーション開発ガイド_v1.2.pdf
→[6 PxR-Service を利用した実行順例]-[6.1 概要]

本人性確認に関するAPIについては、以下のOpenAPIドキュメントにも記載がありますので、こちらも合わせてご確認ください。
https://github.com/Personal-Data-Linkage-Module/pxr-identity-verificate-service/tree/bugfix/%237/openapi

上記内容にてCloseしてよろしければ、その旨を返信願います。
１週間経過後にお返事いただけていない場合は、CLOSEいたします。
Reopenご希望の場合は、返信いただくかコミュニティのSlackにてメンションいただけますようお願いします
