### ISSUE TITLE
アプリケーションとの利用者ID連携情報確認方法について

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#33]
# 確認事項
開発ガイド「6.8 アプリケーションとの利用者ID連携」または、Slackで共有いただいた以下の方法で
アプリケーションと利用者IDが連携済の場合、ログインした後の実施は不要の認識です。
連携済みかどうかを判定する際、どのAPIを使用して判定するのかご教授いただけないでしょうか。

【アプリケーションとの利用者ID連携】
参考：https://cfj.slack.com/archives/C04GCMCFL21/p1683795596083219?thread_ts=1683771222.670799&cid=C04GCMCFL21
```
①住民ポータルで対象アプリを選択して、コード発行
　　※ここで⑤の蓄積同意と共有同意も可能
　　※但し、利用者ID連携完了まで蓄積、共有は行えない
②サービスアプリで何らかのメニュー（例えば、データ連携オプション
　メニュー）から住民ポータル（利用者ID連携画面）にリダイレクト
③利用者ID連携画面でコード入力
　　※利用者ID連携が完了し、蓄積および共有が可能になる
④サービスアプリに戻るとデータ連携オプションが有効になっている
利用者ID連携画面についても、セミナーで説明予定ですが、
ざっくり言うと
　・住民ポータルの一部だが、認証を必要とせず、本人性確認コードで
　　対応する利用者ID連携を完了させるだけの画面
です。
```

**Comment by k-inoue** [comment]
ID連携状態の確認を行うAPIとしては、book-operateサービスの利用者一覧検索API(POST book-operate/user/list)となります。
本APIの仕様につきましては以下OpenAPIをご確認ください。
https://github.com/Personal-Data-Linkage-Module/pxr-book-operate-service/blob/bugfix/%237/openapi/book-operate_user_list.yml

具体的な項目としては、このAPI実行結果として応答データに含まれる「status」の値となります。
０：申請中
１：連携中

上記内容にてCloseしてよろしければ、その旨を返信願います。
１週間経過後にお返事いただけていない場合は、CLOSEいたします。
Reopenご希望の場合は、返信いただくかコミュニティのSlackにてメンションいただけますようお願いします

**Comment by ToshinoriOchiai** [comment]
１週間以上経過しましたので、Close致します。
Close後にもReopenは可能ですので、Slack等でご連絡ください。
