### ISSUE TITLE
【API仕様確認】変更セット登録 (/updateSet/register)

### ISSUE THREAD

**Issue by kizumitani** [Personal-Data-Linkage-Module/pxr-linkage#40]
アプリケーション開発ガイドP44 に記載の内容をベースに下記、仕様確認させてください。

① リクエスト例に指定されている "type": 0 は何を指定するものでしょうか？

② リクエストボディに指定する "ns" は開発ガイドでは[]が指定されていますが、常に空配列の指定でも問題ないでしょうか。そうではない場合、指定が必要な場合と何を指定すればよいかを教えて頂けますでしょうか。

③ リクエストボディに指定する "catalog" > "catalogCode"の値は常にnull指定でよろしいでしょうか？
指定が必要な場合何を指定すればよいか教えて頂けますでしょうか。
また、OpenAPI Spec. では "catalogItemId" と記載されていますが、どちらが正でしょうか。

④リクエストボディに指定する  "catalog" > "comment" (OpenAPI Spec. に記載されているもの) は任意のパラメータでしょうか。
指定した場合はどこにコメントが表示されますでしょうか？

⑤リクエストボディに指定する "catalog" >"template" について、OpenAPI Spec.には "対象テンプレート" と記載されていますが、これは何を指しますでしょうか。

⑥リクエストボディに指定する "catalog" >"template" > "ns": "catalog/ext/xxxxxxxxxxx/event/actor_1000436",について、
 ⑥-1 xxxxxxxxxxx には何を指定すればよいでしょうか？
 ⑥-2 こちらのパスに "event" を指定することでイベントとして登録する指定を行っているという理解であっていますでしょうか？
 ⑥-3 actor_1000436 はアプリ事業者向けに構築した PxR-BlockにログインAPIを投げた際のレスポンスに含まれる"actor" の値を指定すればよいでしょうか？
 

⑦ リクエストボディに指定する  "catalog" >"template" > "name" について、
 ⑦-1 リクエスト例の第1階層の "name": "イベント名(新規作成)", とどのような違いがありますでしょうか。
 ⑦-2 同じ値を指定すればよいでしょうか？
 ⑦-3 また、こちらで指定した値が登録したイベントの名称になる理解であっていますでしょうか？

⑧ リクエストボディに指定する "template" の"_code"について、
 ⑧ -1 常にnullの値を指定で問題ないでしょうか？
 ⑧ -2 もしくはPUTやDELETEのAPIを投げる際は値の指定が必要でしょうか？

⑨ リクエストボディに指定する "template" の"inherit" の値には何を指定すればよいでしょうか？

⑩ リクエストボディに指定する "desription" は処理の中でどのように使用されますでしょうか？

⑪ リクエストボディに指定する "catalog" > "template" > "template" に関して
  ⑪-1 propにしていしたモノの配列がイベントに紐づく理解であっていますでしょうか？
  ⑪-2  "catalog" > "template" > "template">"prop">"key" に指定できる値は、イベントの場合は "thing" のみでしょうか？
  ⑪-3 "catalog" > "template" > "template">"prop">"type"> "candidate">"ns" に指定する必要のある値を教えてください。
  ⑪-4 "catalog" > "template" > "template">"prop">"type"> "candidate">"_code"には何を指定すればよいでしょうか？
  ⑪-5 "catalog" > "template" > "template">"prop">"type"> "candidate">"code">"base"は常にnull指定で問題ないでしょうか？指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？
  ⑪-6 "catalog" > "template" > "template">"prop">"type"> "candidate">"cmatrix"は常にnull指定で問題ないでしょうか？指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？
  ⑪-7 "catalog" > "template" > "template">"prop">"type"> "candidate">"_code"は常にnull指定で問題ないでしょうか？指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？
  ⑪-8 "catalog" > "template" > "template">"prop">"type"> "candidate">"of"は常に"item[]"指定で問題ないでしょうか？他に値の指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？
  ⑪-9 "catalog" > "template" > "template">"prop">"description" はどの処理で使用されますでしょうか？
  ⑪-10 "catalog" > "template" > "template">"prop">"isInherit" はどのような場合にtrue指定する必要がありますでしょうか？
  ⑪-11 "catalog" > "template" > "template">"value"は常にnull指定で問題ないでしょうか？指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？

⑫ リクエストボディに指定する "catalog" > "template" > "template"  > "attribute"  には何の配列を指定すればよいでしょうか。何か値を必ず指定する必要はありますでしょうか？また、こちらで指定した値はどこで利用されますでしょうか？

⑬ リクエストボディに指定する "catalog" > "template" > "template"  > "innner" には何の配列を指定すればよいでしょうか。何か値を必ず指定する必要はありますでしょうか？また、こちらで指定した値はどこで利用されますでしょうか？

⑭リクエストボディに指定する  "attribute " には何の配列を指定すればよいでしょうか。何か値を必ず指定する必要はありますでしょうか？また、こちらで指定した値はどこで利用されますでしょうか？

⑮  リクエストボディに指定する"appendix" には何の配列を指定すればよいでしょうか。何か値を必ず指定する必要はありますでしょうか？また、こちらで指定した値はどこで利用されますでしょうか？

⑯ 各項目の解釈は、イベントカタログの登録、モノカタログの登録、ドキュメントカタログの登録に関してはすべて同様に行って問題ないでしょうか？異なる部分がある場合は教えて頂けないでしょうか？

⑰ APIのレスポンスの値は他の処理で使用しますでしょうか？

![image](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/134504858/ef12ba69-2808-42a9-ba84-cd87f101b450)
![image](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/134504858/f5c912c7-000d-4bdd-993c-1684b7346142)

**Comment by kentaro000** [comment]
@kizumitani 

該当APIに関しまして、OpenAPIにて仕様をまとめましたので、ご参照ください。
https://github.com/Personal-Data-Linkage-Module/pxr-catalog-service/blob/bugfix/%237/openapi/catalog_updateSet_register.yml

> ① リクエスト例に指定されている "type": 0 は何を指定するものでしょうか？

"type"は、未使用のパラメータです。指定頂く必要はありません。

> ② リクエストボディに指定する "ns" は開発ガイドでは[]が指定されていますが、常に空配列の指定でも問題ないでしょうか。
> そうではない場合、指定が必要な場合と何を指定すればよいかを教えて頂けますでしょうか。

"ns"は、対象のカタログの名前空間に対して、操作する際に指定します。操作は、登録・更新・削除が可能です。
指定方法については、OpenAPIをご参照ください。

> ③ リクエストボディに指定する "catalog" > "catalogCode"の値は常にnull指定でよろしいでしょうか？
> 指定が必要な場合何を指定すればよいか教えて頂けますでしょうか。
> また、OpenAPI Spec. では "catalogItemId" と記載されていますが、どちらが正でしょうか。

"catalogCode"は、対象のカタログ項目コードを指定します。追加する場合にはnullを、更新・削除する場合には追加時に採番されたコードを指定してください。
指定が必要な場合についてですが、catalogItemIdを指定してください。

> ④リクエストボディに指定する "catalog" > "comment" (OpenAPI Spec. に記載されているもの) は任意のパラメータでしょうか。
> 指定した場合はどこにコメントが表示されますでしょうか？

"comment"は任意パラメータです。表示機能はありませんので表示はされません。
変更セットカタログテーブルに追加する申請情報のコメントになります。
commentの標準ユースケースとしてAPプロバイダが変更申請を行い、運営組織が承認といったケースにおいて、変更内容（comment）を登録し、それを確認し承認するようなユースケースを想定しております。（API利用側のUIにて利用）

> ⑤リクエストボディに指定する "catalog" >"template" について、
> OpenAPI Spec.には "対象テンプレート" と記載されていますが、これは何を指しますでしょうか。

編集する対象のカタログのテンプレートを指します。この項目にて、編集したい内容を定義します。
指定方法については、OpenAPIをご参照ください。

> ⑥リクエストボディに指定する "catalog" >"template" > "ns": "catalog/ext/xxxxxxxxxxx/event/actor_1000436",について、

> ⑥-1 xxxxxxxxxxx には何を指定すればよいでしょうか？

編集する対象のカタログをアクティベートする際に指定した拡張名前空間名を指定します。
具体的には利用環境で実施した初期カタログ投入時（下記手順）の{ext_name}に対して設定した値となります。
<手順>
構築事業者向けセミナー_STEP2手順詳細.xlsx
└2-4-2 設定値の変更

> ⑥-2 こちらのパスに "event" を指定することでイベントとして登録する指定を行っているという理解であっていますでしょうか？

ご認識通りです。

> ⑥-3 actor_1000436 はアプリ事業者向けに構築した PxR-BlockにログインAPIを投げた際のレスポンスに含まれる"actor" の値を指定すればよいでしょうか？

はい。対象のカタログを利用するアプリケーションのアクターコードを指定します。

> ⑦ リクエストボディに指定する "catalog" >"template" > "name" について、
> ⑦-1 リクエスト例の第1階層の "name": "イベント名(新規作成)", とどのような違いがありますでしょうか。
> ⑦-2 同じ値を指定すればよいでしょうか？

"name"(第1階層)は、変更セットの名称です。
"catalog.template.catalogItem.name"は、対象のカタログ項目の名称です。
違う意味を示す項目ですが、同じ値でも問題はありません。

> ⑦-3 また、こちらで指定した値が登録したイベントの名称になる理解であっていますでしょうか？

イベントのカタログを指定している場合は、ご認識通りです。

> ⑧ リクエストボディに指定する "template" の"_code"について、
> ⑧ -1 常にnullの値を指定で問題ないでしょうか？
> ⑧ -2 もしくはPUTやDELETEのAPIを投げる際は値の指定が必要でしょうか？

追加の場合には常にnullで問題ありません。
流通制御SPにより承認されるとコード（catalogCode）が採番されます。任意の値を指定することも可能です。
更新や削除の場合は、コード（catalogCode）を指定します。仕様はOpenAPIをご参照ください。

> ⑨ リクエストボディに指定する "template" の"inherit" の値には何を指定すればよいでしょうか？

継承するカタログ項目を指定します。

> ⑩ リクエストボディに指定する "desription" は処理の中でどのように使用されますでしょうか？

処理では使用しません。

> ⑪ リクエストボディに指定する "catalog" > "template" > "template" に関して
⑪の説明に際し、概念としてイベントのデータカタログにおけるPropは該当イベントに紐付け可能なモノの前提条件（ns、型、コード、継承元など）を定義する項目であり、ここで設定された前提条件に合致するモノが候補として認識され、それに準じないものは紐付け不可となります。
（イベントのデータカタログとして紐付けるモノのルールを定め、統一する為の仕組み）

> ⑪-1 propにしていしたモノの配列がイベントに紐づく理解であっていますでしょうか？

イベントカタログのthingプロパティに指定したモノの配列がそのイベントに紐づきます。

> ⑪-2 "catalog" > "template" > "template">"prop">"key" に指定できる値は、イベントの場合は "thing" のみでしょうか？

任意のプロパティを追加できます。
単純に蓄積/共有する場合はイベントカタログに新規プロパティは必要ありませんので、thingプロパティに紐づけるもののカタログコードを指定してください。

> ⑪-3 "catalog" > "template" > "template">"prop">"type"> "candidate">"ns" に指定する必要のある値を教えてください。

プロパティに設定可能なカタログ項目が存在する名前空間リストを設定します。

> ⑪-4 "catalog" > "template" > "template">"prop">"type"> "candidate">"_code"には何を指定すればよいでしょうか？

プロパティに設定可能な候補値を定義をするため、設定可能なカタログ項目リストを指定します。

> ⑪-5 "catalog" > "template" > "template">"prop">"type"> "candidate">"code">"base"は常にnull指定で問題ないでしょうか？
> 指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？

プロパティに設定可能なカタログの継承元カタログ項目を指定します。本パラメータに設定したカタログ項目を継承元とするカタログ項目を設定候補値とします。

> ⑪-6 "catalog" > "template" > "template">"prop">"type"> "candidate">"cmatrix"は常にnull指定で問題ないでしょうか？
> 指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？

"cmatrix"は、未使用のパラメータです。指定頂く必要はありません。

> ⑪-7 "catalog" > "template" > "template">"prop">"type"> "candidate">"_code"は常にnull指定で問題ないでしょうか？
> 指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？

プロパティに設定可能な候補値を設定したい場合に指定します。

> ⑪-8 "catalog" > "template" > "template">"prop">"type"> "candidate">"of"は常に"item[]"指定で問題ないでしょうか？
> 他に値の指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？

プロパティに設定可能な型を定義します。設定可能な型の種類など指定方法は、OpenAPIファイルをご参照ください。

> ⑪-9 "catalog" > "template" > "template">"prop">"description" はどの処理で使用されますでしょうか？
処理では使用しません。

> ⑪-10 "catalog" > "template" > "template">"prop">"isInherit" はどのような場合にtrue指定する必要がありますでしょうか？

"isInherit"は、未使用のパラメータです。指定頂く必要はありません。

> ⑪-11 "catalog" > "template" > "template">"value"は常にnull指定で問題ないでしょうか？
> 指定が必要な場合、どのような際に指定が必要で何を指定すればよいでしょうか？

プロパティ値の代入定義リストを指定します。
ここで設定された値は "catalog.template.template.prop"の要素で"key"が一致するプロパティ値として設定されます。
カタログ取得時のValueとして固定値を指定したい場合に利用する項目であり、一例は下記の通りです。
（例）propで指定した要素のうち、"password-generations-number"を 4 を固定で設定。カタログ取得時にvalue:4で返却される
＜変更セット登録（カタログ更新）リクエストイメージ＞
：
{
"key": "password-generations-number",
"value": 4
}
：

＜カタログ取得レスポンスイメージ＞
：
"password-generations-number": 4,
：

> ⑫ リクエストボディに指定する "catalog" > "template" > "template" > "attribute" には何の配列を指定すればよいでしょうか。
> 何か値を必ず指定する必要はありますでしょうか？また、こちらで指定した値はどこで利用されますでしょうか？

"attribute"は、未使用のパラメータです。指定頂く必要はありません。

> ⑬ リクエストボディに指定する "catalog" > "template" > "template" > "innner" には何の配列を指定すればよいでしょうか。
> 何か値を必ず指定する必要はありますでしょうか？また、こちらで指定した値はどこで利用されますでしょうか？

"innner"は、任意のパラメータです。指定頂く必要はありません。
内部クラスを定義するためのリストを指定できます。

> ⑭リクエストボディに指定する "attribute " には何の配列を指定すればよいでしょうか。
> 何か値を必ず指定する必要はありますでしょうか？また、こちらで指定した値はどこで利用されますでしょうか？

"attribute"は、未使用のパラメータです。指定頂く必要はありません。

> ⑮ リクエストボディに指定する"appendix" には何の配列を指定すればよいでしょうか。
> 何か値を必ず指定する必要はありますでしょうか？また、こちらで指定した値はどこで利用されますでしょうか？

"appendix"は、未使用のパラメータです。指定頂く必要はありません。

> ⑯ 各項目の解釈は、イベントカタログの登録、モノカタログの登録、ドキュメントカタログの登録に関してはすべて同様に行って問題ないでしょうか？
> 異なる部分がある場合は教えて頂けないでしょうか？

同様に解釈頂いて構いません。

> ⑰ APIのレスポンスの値は他の処理で使用しますでしょうか？

レスポンスに変更セットID（"id"）が返却されます。この変更セットIDを使ってカタログ作成申請を実施します。
詳細は、接続事業者セミナー資料STEP1-6をご参照ください。

**Comment by kentaro000** [comment]
上記内容にてCloseしてよろしければ、その旨を返信願います。
１週間経過後にお返事いただけていない場合は、CLOSEいたします。
Reopenご希望の場合は、返信いただくかコミュニティのSlackにてメンションいただけますようお願いします

**Comment by ToshinoriOchiai** [comment]
１週間経過しましたので、Close致します。
Close後にもReopenは可能ですので、Slack等でご連絡ください。
