### ISSUE TITLE
【API仕様確認】 利用者一覧検索 (/book-operate/user/list)

### ISSUE THREAD

**Issue by kizumitani** [Personal-Data-Linkage-Module/pxr-linkage#41]
アプリケーション開発ガイドP89の例をベースに下記確認させてください。

①リクエストボディの必須/任意、デフォルト値は下記で正しいでしょうか。
"userId" : 必須
"establishAt" : 必須、start, endを指定しない場合はnullを指定
"includeRequest" : 任意 、初期値はfalse

②"userId"に指定する値は、個人ログインAPIで指定する "loginId" と同一の値であっていますでしょうか。

③レスポンスに含まれる "app" の項目には何の値が返却されていますでしょうか？

④レスポンスに含まれる "store" 以下の "document", "event", "thing" の値は個人が同意済みのデータ種に紐づく値がすべて格納されている理解であっていますでしょうか。

⑤userInformation に値が格納されることはありますでしょうか？また、格納される場合は何が格納されますか？

⑥レスポンスに含まれるデータが格納されているオブジェクトは常に一つでしょうか？それとも複数になることはありますでしょうか？開発ガイドでは {}が入れ子になっているため確認です。
![image](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/134504858/0c9fbaad-ea71-4fb3-97b4-e537480a1798)
![image](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/134504858/4559d4d2-207c-49df-a9f2-bd384544e416)

**Comment by ToshinoriOchiai** [comment]
まず、本APIの仕様について、説明します。

本APIは、My-Condition-Bookテーブルから取得したレコードを返却します。
My-Condition-Bookテーブルの抽出条件をリクエストにて、指定できます。
クエリで指定した条件はAND条件として検索されます。
　My-Condition-Book.利用者ID IN リクエスト.userId配列
　My-Condition-Book.開設日時 >= リクエスト.establishAt.start
　My-Condition-Book.開設日時 <= リクエスト.establishAt.end

userIdは、複数指定することも可能です。
establishAtは、ISO8601(JST)で指定ください。
includeRequestが、Trueの場合は、NotificationServiceから取得します。

[リクエスト例]
~~~ javascript
{
"userId": [
"useTestUser000002",
"useTestUser000003"
],
"establishAt": {
"start": "2020-01-01T00:00:00.000+0900",
"end": "2020-03-01T00:00:00.000+0900"
},
"includeRequest": true
}

~~~

次に、ご質問に対して、ご回答致します。

> ①リクエストボディの必須/任意、デフォルト値は下記で正しいでしょうか。
> "userId" : 必須
> "establishAt" : 必須、start, endを指定しない場合はnullを指定
> "includeRequest" : 任意 、初期値はfalse

下記３項目全て任意です。
・"userId"
・"establishAt"
・"includeRequest"
ただし、リクエストボディ自体が空の場合はエラーになりますので、全件検索実施の際は任意の項目でNullを指定下さい。

> ②"userId"に指定する値は、個人ログインAPIで指定する "loginId" と同一の値であっていますでしょうか。

お問合せ頂いた「6.11 My-Condition-Dataの 蓄積」は、"アプリケーションプロバイダー"がログインして利用する説明をしております。
userIdは、該当のアプリケーションプロバイダーにて、利用者ID連携されたIDです。

> ③レスポンスに含まれる "app" の項目には何の値が返却されていますでしょうか？

アプリケーションカタログコードです。
該当のアプリケーションプロバイダーのアプリケーションカタログコードを返却します。

> ④レスポンスに含まれる "store" 以下の "document", "event", "thing" の値は個人が同意済みのデータ種に紐づく値がすべて格納されている理解であっていますでしょうか。

My-Condition-Dataに格納されている各値が返却されます。
My-Condition-Dataに格納されるのは、個人が同意済みのデータです。

> ⑤userInformation に値が格納されることはありますでしょうか？また、格納される場合は何が格納されますか？

利用者一覧検索のレスポンスでは、userInformationに値は格納されません。

> ⑥レスポンスに含まれるデータが格納されているオブジェクトは常に一つでしょうか？それとも複数になることはありますでしょうか？開発ガイドでは {}が入れ子になっているため確認です。

大括弧と中括弧の誤記です。失礼しました。

正）
~~~
[
　{
　　:
　}
]
~~~
誤）
~~~
{
　{
　　:
　}
}
~~~
