### ISSUE TITLE
【API仕様確認】ドキュメント蓄積 (/book-operate/document/{userId})

### ISSUE THREAD

**Issue by kizumitani** [Personal-Data-Linkage-Module/pxr-linkage#42]
アプリケーション開発ガイドP90の例をベースに下記確認させてください。

① "userId"に指定する値は、個人ログインAPIで指定する "loginId" と同一の値であっていますでしょうか。

②リクエストボディに指定する"_code"は "/bookoperate/user/list" のAPIのレスポンスに含まれる"store" > "document"の値を指定する形であっていますでしょうか。

③リクエストボディに指定する "wf"> "code" には何を指定すればよいでしょうか。またindexの値には何を指定すればよいでしょうか？

④リクエストボディに指定する "wf"> "wf" には何を指定すればよいでしょうか。またindexの値には何を指定すればよいでしょうか？

⑤リクエストボディに指定する "wf"> "role" には何を指定すればよいでしょうか。またindexの値には何を指定すればよいでしょうか？

⑥ リクエストボディに指定する "wf"> "staffId" には何を指定すればよいでしょうか。またindexの値には何を指定すればよいでしょうか？

⑦ リクエストボディに指定する "capter" には何を指定すればよいでしょうか。title, event, sourceIdそれぞれについて教えて頂けないでしょうか？

⑧ リクエストボディに指定する "code" には何を指定すればよいでしょうか。"_code"との違いは何になりますでしょうか？

⑨ リクエストボディに指定する "createdAt" には何を指定すればよいでしょうか。

⑩リクエストボディに指定する "id" のvalueは常にnullでしょうか？またindexの値には何を指定すればよいでしょうか？

⑪ リクエストボディに指定する "sourceId" には何を指定すればよいでしょうか

⑫ リクエストボディに指定する "app" は常にnullでしょうか

⑬  リクエストボディに指定する "userId" はパスパラメータに指定する値と同じものでしょうか？またindexには何を指定すればよいでしょうか？

⑭ レスポンスの値はリクエストで指定した値がそのまま格納されて返却される理解であっていますでしょうか？
![image](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/134504858/8b6733ab-1866-444a-abe2-689e6792fc0b)

**Comment by ToshinoriOchiai** [comment]
該当APIに関しまして、OpenAPIにて仕様をまとめましたので、ご参照ください。
https://github.com/Personal-Data-Linkage-Module/pxr-book-operate-service/blob/bugfix/%237/openapi/book-operate_document_userId.yml

ただし、一部誤記がありますので、別途修正予定です。
　誤）イベント蓄積
　正）ドキュメント蓄積

> ① "userId"に指定する値は、個人ログインAPIで指定する "loginId" と同一の値であっていますでしょうか。

同一の値ではありません。

個人用ログインAPI（[アプリケーション開発ガイド P.54]POST /operator/ind/login）で指定する"loginId" は、流通制御サービスプロバイダーにて個人オペレータがBook開設時に指定するIDです。 "loginId" は、"pxrId" と一意に紐づくIDです。
ドキュメント蓄積API（質問対象のAPI）で指定する"userId"は、蓄積対象の利用者IDを指し、アプリケーションプロバイダーにてオペレータが利用者を一意に特定するためIDです。"userId"は、利用者作成API (POST /book-operate/user) のレスポンスの値です。

> ②リクエストボディに指定する"_code"は "/bookoperate/user/list" のAPIのレスポンスに含まれる
> "store" > "document"の値を指定する形であっていますでしょうか。
> ③リクエストボディに指定する "wf"> "code" には何を指定すればよいでしょうか。
> またindexの値には何を指定すればよいでしょうか？
> ④リクエストボディに指定する "wf"> "wf" には何を指定すればよいでしょうか。
> またindexの値には何を指定すればよいでしょうか？
> ⑤リクエストボディに指定する "wf"> "role" には何を指定すればよいでしょうか。
> またindexの値には何を指定すればよいでしょうか？
> ⑥ リクエストボディに指定する "wf"> "staffId" には何を指定すればよいでしょうか。
> またindexの値には何を指定すればよいでしょうか？

②～⑥について、"_code"と"wf"は未使用のパラメータです。指定頂く必要はありません。

> ⑦ リクエストボディに指定する "capter" には何を指定すればよいでしょうか。
> title, event, sourceIdそれぞれについて教えて頂けないでしょうか？

"capter"は、蓄積対象ドキュメントに含む各々の情報をグループ化し、個人が理解しやすくする用途で任意に設定します。設定値の仕様については、OpenAPIをご参照ください。

> ⑧ リクエストボディに指定する "code" には何を指定すればよいでしょうか。
> "_code"との違いは何になりますでしょうか？

"code"は、蓄積するドキュメントのカタログ項目コードを指定します。変更セット登録APIで設定したドキュメントカタログのコード値を指定してください。

> ⑨ リクエストボディに指定する "createdAt" には何を指定すればよいでしょうか。

"createdAt"には、ドキュメントの作成日時を指定してください。

> ⑩リクエストボディに指定する "id" のvalueは常にnullでしょうか？
> またindexの値には何を指定すればよいでしょうか？

"id"のvalueは、メソッドによって異なります。登録の場合にはnullを指定してください。更新の場合には対象のidを指定してください。index には 2_1_1 を設定します。

> ⑪ リクエストボディに指定する "sourceId" には何を指定すればよいでしょうか

"sourceId"は、蓄積対象ドキュメントに割り当てる識別子です。ただし、必須項目ではありません。
ドキュメントの更新または削除のAPIにて、対象の指定に利用できます。例えば、蓄積元システムで採番したデータ識別子を本項目に付与することで、本モジュールが付与するデータ識別子を使わずに更新、削除が可能です。

> ⑫ リクエストボディに指定する "app" は常にnullでしょうか

"app"は、nullではありません。ドキュメント蓄積を行うアプリケーションのカタログ項目コードを指定してください。詳細は、OpenAPIまたは「接続事業者向けセミナー資料 STEP3-1」をご参照ください。

> ⑬ リクエストボディに指定する "userId" はパスパラメータに指定する値と同じものでしょうか？
> またindexには何を指定すればよいでしょうか？

ご認識通りです。indexは3_6_1を指定してください。

> ⑭ レスポンスの値はリクエストで指定した値がそのまま格納されて返却される理解であっていますでしょうか？

ドキュメント識別子が採番された状態でレスポンスが返却されます。

---
上記内容を最終回答とさせて頂きます。
本件に関して、追加でのご確認等があれば、ご返信お願い致します。
ご返信がないまま、1週間経過しましたら、Closeさせて頂きます。
Close後にもReopenは可能ですので、Slack等でご連絡ください。

**Comment by kizumitani** [comment]
@ToshinoriOchiai 
ご回答ありがとうございました。
内容確認させて頂き、現時点では追加の質問はございませんのでチケットはクローズとして頂いて問題ございません。

**Comment by ToshinoriOchiai** [comment]
ご確認ありがとうございます。
クローズさせて頂きます。何かあれば、ご連絡ください。
引き続き、宜しくお願い致します。
