### ISSUE TITLE
【API仕様確認】モノ蓄積 (/bookoperate/thing/{userId}/{eventId})

### ISSUE THREAD

**Issue by kizumitani** [Personal-Data-Linkage-Module/pxr-linkage#44]
アプリケーション開発ガイドP95の例をベースに下記確認させてください。

① パスパラメータ―に指定するeventIdは イベント蓄積のAPIのレスポンス以外から取得する方法はありますでしょうか？
② リクエストボディに指定する"_code"は "/bookoperate/user/list" のAPIのレスポンスに含まれる"store" > "thing"の値を指定であっていますでしょうか。
③ リクエストボディに指定する"app" > "code" には何を指定すればよいでしょうか？
④ リクエストボディに指定する"app" > "app" には何を指定すればよいでしょうか？
⑤ リクエストボディに指定する"code" のindexには何を指定すればよいでしょうか？ また、"_value"に指定する値は ③の "_code" で指定した値と同じものでしょうか？
⑥ リクエストボディに指定する"env" には何を指定すればよいでしょうか？
⑦ リクエストボディに指定する"envelope" > "resourceType" には何を指定すればよいでしょうか？
⑧ リクエストボディに指定する"envelope" > "identifier" には何を指定すればよいでしょうか？
⑨ リクエストボディに指定する"envelope" > "subject" には何を指定すればよいでしょうか？
⑩ リクエストボディに指定する"envelope" > "issuedate" には何を指定すればよいでしょうか？
⑪ リクエストボディに指定する"envelope" > "class" には何を指定すればよいでしょうか？
⑫ リクエストボディに指定する"envelope" > "classhistory" には何を指定すればよいでしょうか？
⑬ リクエストボディに指定する"referenceNumber" には何を指定すればよいでしょうか？
⑭ リクエストボディに指定する"invoiceSerialNumber" には何を指定すればよいでしょうか？
⑮ リクエストボディに指定する"invoiceBranceNumber" には何を指定すればよいでしょうか？
⑯ リクエストボディに指定する"departmentCode" には何を指定すればよいでしょうか？
⑰ リクエストボディに指定する"paymentClass" には何を指定すればよいでしょうか？
⑱ リクエストボディに指定する"depositThisTime" には何を指定すればよいでしょうか？
⑲ リクエストボディに指定する"lastDeposit" には何を指定すればよいでしょうか？
⑳ リクエストボディに指定する"id" には何を指定すればよいでしょうか？
㉑ リクエストボディに指定する"sourceId" には何を指定すればよいでしょうか？
㉒ リクエストボディに指定する"wf" には何を指定すればよいでしょうか？
㉓ レスポンスの値に格納される "id" は蓄積したデータを一意に特定するものでしょうか？

<img width="185" alt="image" src="https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/134504858/595440c6-6c9f-41b8-80aa-30db69882f40">

**Comment by kizumitani** [comment]
@smit-akiyama 
こちらのAPIの接続事業者側の実装方法について、下記の想定で正しいか教えて頂けないでしょうか？

 ↓ ログインAPIを実行し、sessionIdを取得。 (以降の処理でoperator_type2_sessionヘッダーに指定) 
 ↓ 対象ユーザーのuserIdをリクエストパラメータに指定し、利用者一覧検索APIを実行、蓄積可能なデータ項目の一覧が返却される。
 ↓ 蓄積しようとしているデータ項目が蓄積可能かを確認し、データ蓄積APIを実行。

**Comment by ToshinoriOchiai** [comment]
該当APIに関しまして、OpenAPIにて仕様をまとめましたので、ご参照ください。
https://github.com/Personal-Data-Linkage-Module/pxr-book-operate-service/blob/bugfix/%237/openapi/book-operate_thing_userId_eventId.yml

> ① パスパラメータ―に指定するeventIdは イベント蓄積のAPIのレスポンス以外から取得する方法はありますでしょうか？

他にも、場面やアクタによっては、eventIdを返却するAPIはございますが、ご質問の意図として、どういった場面での取得を想定されているかをご明示ください。

本APIをご利用の上で、eventIdを取得する意図として回答としては、アプリケーションからモノ蓄積APIを呼ぶ上で、対象のモノに紐づくイベントを指定するためのeventIdですので、ガイド記載の通り、イベント蓄積したレスポンスからeventIdを取得頂くことを想定しております。

蓄積する側（共有元）ではなく、共有先でeventIdが必要な場合などを想定してのご質問とも見受けられましたが、ご質問対象のAPIと主旨が異なるため、別Issueでのご質問頂くのが適切かと思います。

> ② リクエストボディに指定する"_code"は "/bookoperate/user/list" のAPIのレスポンスに含まれる"store" > "thing"の値を指定であっていますでしょうか。

_codeは、未使用のパラメータです。指定頂く必要はありません。

> ③ リクエストボディに指定する"app" > "code" には何を指定すればよいでしょうか？
> ④ リクエストボディに指定する"app" > "app" には何を指定すればよいでしょうか？

appは、下記の通り、モノ追加を行うアプリケーションのカタログ項目コードを指定ください。
　app.code：対象アプリケーションのアクターカタログコード
　app.app ：対象アプリケーションのアプリケーションカタログコード

> ⑤ リクエストボディに指定する"code" のindexには何を指定すればよいでしょうか？
> また、"_value"に指定する値は ③の "_code" で指定した値と同じものでしょうか？

codeは、下記の通り、モノのカタログ項目コードを指定ください。
　code.index：4_1_2
　code.value：蓄積する thing のカタログコード

> ⑥ リクエストボディに指定する"env" には何を指定すればよいでしょうか？

非パーソナルデータをパーソナルデータの一部として保存しておくプロパティとして利用します。
オプションなので、不要であれば、指定は不要です。

例えば、センサ情報などの非パーソナルデータを、パーソナルデータと紐づける場合、
カタログを定義しておき、envで指定します。

https://github.com/Personal-Data-Linkage-Module/pxr-linkage/blob/develop/delivery/catalog/built_in/env/thing/sensor/sensor_item.json

> ⑦ リクエストボディに指定する"envelope" > "resourceType" には何を指定すればよいでしょうか？
> ⑧ リクエストボディに指定する"envelope" > "identifier" には何を指定すればよいでしょうか？
> ⑨ リクエストボディに指定する"envelope" > "subject" には何を指定すればよいでしょうか？
> ⑩ リクエストボディに指定する"envelope" > "issuedate" には何を指定すればよいでしょうか？
> ⑪ リクエストボディに指定する"envelope" > "class" には何を指定すればよいでしょうか？
> ⑫ リクエストボディに指定する"envelope" > "classhistory" には何を指定すればよいでしょうか？

envelopeは、開発ガイドの誤りですので、指定不要です。

> ⑬ リクエストボディに指定する"referenceNumber" には何を指定すればよいでしょうか？
> ⑭ リクエストボディに指定する"invoiceSerialNumber" には何を指定すればよいでしょうか？
> ⑮ リクエストボディに指定する"invoiceBranceNumber" には何を指定すればよいでしょうか？
> ⑯ リクエストボディに指定する"departmentCode" には何を指定すればよいでしょうか？
> ⑰ リクエストボディに指定する"paymentClass" には何を指定すればよいでしょうか？
> ⑱ リクエストボディに指定する"depositThisTime" には何を指定すればよいでしょうか？
> ⑲ リクエストボディに指定する"lastDeposit" には何を指定すればよいでしょうか？

これらはガイドの記載上、envelope配下の項目です。
⑦～⑫で回答の通り、envelopeは、開発ガイドの誤りですので、指定不要です。

> ⑳ リクエストボディに指定する"id" には何を指定すればよいでしょうか？

idは、下記の通り、モノのデータ識別子を指定ください。
　id.index：4_1_1
　id.value：登録時にはNull（更新時には更新対象のidを指定します）

> ㉑ リクエストボディに指定する"sourceId" には何を指定すればよいでしょうか？

sourceId は、蓄積対象のイベント・モノに割り当てる識別子を指定できます。
複数のイベントに同一sourceIdを指定することも可能です。
イベント更新API又はイベント削除APIで対象の指定に利用できます。

サービス事業者側のデータから蓄積対象データとしてイベント・モノを蓄積します。
サービス事業者側のデータを更新した場合や、蓄積対象から削除する場合に、
一括で更新や削除する際にご利用頂くことを想定しています。

ご利用頂く想定が無い場合、sourceIdを指定する必要はありません。
ただし、APIのパラメータとしては必須項目のため、NULLを指定ください。

> ㉒ リクエストボディに指定する"wf" には何を指定すればよいでしょうか？

wfは、未使用のパラメータです。指定頂く必要はありません。

> ㉓ レスポンスの値に格納される "id" は蓄積したデータを一意に特定するものでしょうか？

はい。リクエストのパスパラメータである"userId"、"eventId"と組み合わせて一意になります。

**Comment by ToshinoriOchiai** [comment]
別途コメントにて、ご質問頂いている下記について、ご回答致します。

> こちらのAPIの接続事業者側の実装方法について、下記の想定で正しいか教えて頂けないでしょうか？
> 
> ↓ ログインAPIを実行し、sessionIdを取得。 (以降の処理でoperator_type2_sessionヘッダーに指定)
> ↓ 対象ユーザーのuserIdをリクエストパラメータに指定し、利用者一覧検索APIを実行、蓄積可能なデータ項目の一覧が返却される。
> ↓ 蓄積しようとしているデータ項目が蓄積可能かを確認し、データ蓄積APIを実行。


接続事業者側の実装方法については、接続事業者様向けセミナー資料のSTEP3-1をご確認ください。
なお、概ね流れは合っていますが、利用者一覧検索APIは対象ブロック内に登録されている利用者が返却され、蓄積可能なデータ項目の一覧が返却されるわけではありません。

また対象ユーザーが蓄積可能かを確認するためには蓄積同意状況を調べる必要があります。そのフローに関しては、上記接続事業者様向けセミナー資料のSTEP2-3もご参照頂ければと思います。

本質問のAPIと直接関連しないため、追加質問等あれば、別Issueを発行頂けると幸いです。

参考）接続事業者様向けセミナー資料
https://github.com/Personal-Data-Linkage-Module/pxr-linkage/blob/develop/doc/%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC/20230629_%E3%83%91%E3%83%BC%E3%82%BD%E3%83%8A%E3%83%AB%E3%83%87%E3%83%BC%E3%82%BF%E9%80%A3%E6%90%BA%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB_%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC%E8%B3%87%E6%96%99%EF%BC%88%E6%8E%A5%E7%B6%9A%E4%BA%8B%E6%A5%AD%E8%80%85%E6%A7%98%E5%90%91%E3%81%91%EF%BC%89/%E3%83%91%E3%83%BC%E3%82%BD%E3%83%8A%E3%83%AB%E3%83%87%E3%83%BC%E3%82%BF%E9%80%A3%E6%90%BA%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB_%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC%E8%B3%87%E6%96%99%EF%BC%88%E6%8E%A5%E7%B6%9A%E4%BA%8B%E6%A5%AD%E8%80%85%E6%A7%98%E5%90%91%E3%81%91%EF%BC%89.pdf

https://github.com/Personal-Data-Linkage-Module/pxr-linkage/blob/develop/doc/%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC/20230629_%E3%83%91%E3%83%BC%E3%82%BD%E3%83%8A%E3%83%AB%E3%83%87%E3%83%BC%E3%82%BF%E9%80%A3%E6%90%BA%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB_%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC%E8%B3%87%E6%96%99%EF%BC%88%E6%8E%A5%E7%B6%9A%E4%BA%8B%E6%A5%AD%E8%80%85%E6%A7%98%E5%90%91%E3%81%91%EF%BC%89/%E6%8E%A5%E7%B6%9A%E4%BA%8B%E6%A5%AD%E8%80%85%E5%90%91%E3%81%91%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC_STEP3-1%E6%89%8B%E9%A0%86%E8%A9%B3%E7%B4%B0.xlsx

---

上記内容を本Issueの最終回答とさせて頂きます。
本件に関して、追加でのご確認等があれば、ご返信お願い致します。
ご返信がないまま、1週間経過しましたら、Closeさせて頂きます。
Close後にもReopenは可能ですので、Slack等でご連絡ください。

**Comment by ToshinoriOchiai** [comment]
１週間以上経過しましたので、Close致します。
Close後にもReopenは可能ですので、Slack等でご連絡ください。
