### ISSUE TITLE
【API仕様確認】データ共有 (/book-operate/share)

### ISSUE THREAD

**Issue by kizumitani** [Personal-Data-Linkage-Module/pxr-linkage#45]
アプリケーション開発ガイドP97の例をベースに下記確認させてください。

① リクエストボディの必須項目は何になりますでしょうか？
② リクエストボディの "event" には何の値を指定すればよいでしょうか？
③ リクエストボディには "event"や "thing" を複数指定することは可能でしょうか？
④ レスポンスボディの値は、リクエストボディに"event"を指定した場合、該当する "event" とそれに紐づく"thing" がすべて配列の形で返却される仕様になっていますでしょうか？

![image](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/134504858/82692ea6-de70-486b-8091-c07aa624f05d)

**Comment by ToshinoriOchiai** [comment]
該当APIに関しまして、OpenAPIにて仕様をまとめましたので、ご参照ください。
https://github.com/Personal-Data-Linkage-Module/pxr-book-operate-service/blob/bugfix/%237/openapi/book-operate_share.yml

本APIはデータ取得条件を基にデータ共有APIを呼び出し、データを取得します。
このデータ取得条件として、ドキュメント・イベント・モノを指定できます。

> ① リクエストボディの必須項目は何になりますでしょうか？

APIとしての必須項目は、"userId"です。共有対象とするデータに紐づく利用者IDです。

> ② リクエストボディの "event" には何の値を指定すればよいでしょうか？

検索対象イベントのカタログコードとカタログコードのバージョンを指定します。

> ③ リクエストボディには "event"や "thing" を複数指定することは可能でしょうか？

はい。配列として複数指定できます。

> ④ レスポンスボディの値は、リクエストボディに"event"を指定した場合、該当する "event" と
> それに紐づく"thing" がすべて配列の形で返却される仕様になっていますでしょうか？

はい、ご認識通りです。
リクエストボディに"event"を指定した場合、該当する "event"とそれに紐づくすべての"thing"が配列の形で返却されます。

---

上記内容を最終回答とさせて頂きます。
本件に関して、追加でのご確認等があれば、ご返信お願い致します。
ご返信がないまま、1週間経過しましたら、Closeさせて頂きます。
Close後にもReopenは可能ですので、Slack等でご連絡ください。

**Comment by smit-akiyama** [comment]
本件に関しまして、上記回答から1週間経過しましたのでCloseさせていただきます。
