### ISSUE TITLE
【API仕様確認】URL 発行 /identity-verificate/url/issue

### ISSUE THREAD

**Issue by kizumitani** [Personal-Data-Linkage-Module/pxr-linkage#46]
アプリケーション開発ガイドP64の例をベースに下記確認させてください。

① urlTypeの値は何を示しますでしょうか？ (0はxxx用でyyyの際に使用するのように教えて頂けると幸いです。)
② "userId" は "3. オペレータIDの取得のresponseのuserIdで設定" と記載がありますが、どのドキュメントの何ページに記載されていますでしょうか？

![image](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/134504858/07771b36-8002-4830-bfc8-83f38771f722)

**Comment by ToshinoriOchiai** [comment]
該当APIに関しまして、OpenAPIにて仕様をまとめましたので、ご参照ください。

https://github.com/Personal-Data-Linkage-Module/pxr-identity-verificate-service/blob/bugfix/%237/openapi/identity-verificate_url_issue.yml

本APIは、本人性確認を行うページのURLを発行します。

> ① urlTypeの値は何を示しますでしょうか？
> (0はxxx用でyyyの際に使用するのように教えて頂けると幸いです。)

発行URL種別として、発行する対象を指定します。
指定する値は"1"（アクター）を指定してください。

> ② "userId" は "3. オペレータIDの取得のresponseのuserIdで設定" と記載がありますが、どのドキュメントの何ページに記載されていますでしょうか？

こちらは、ドキュメントの誤記です。申し訳ありません。
オペレータIDは、 pxr-operator-service の [POST /.] （追加API）実行時に発行されたIDをご指定ください。

---

上記内容を最終回答とさせて頂きます。
本件に関して、追加でのご確認等があれば、ご返信お願い致します。
ご返信がないまま、1週間経過しましたら、Closeさせて頂きます。
Close後にもReopenは可能ですので、Slack等でご連絡ください。

**Comment by kizumitani** [comment]
@ToshinoriOchiai 
ご回答ありがとうございました。
こちら追加質問はございませんのでクローズして頂いて問題ございません。

**Comment by ToshinoriOchiai** [comment]
ご確認ありがとうございます。
クローズさせて頂きます。何かあれば、ご連絡ください。
引き続き、宜しくお願い致します。
