### ISSUE TITLE
特定の条件下で、外部から正規の認証を経ずにAPIを利用できてしまう

### ISSUE THREAD

**Issue by itoshot** [Personal-Data-Linkage-Module/pxr-linkage#49]
外部APIを呼び出す際は、クッキーのセッション情報を用いてオペレーターサービス.セッションチェックAPIを通してセッションの取得（= ログイン状態の確認）を行う。
一方、API内でプロキシを介してAPIを呼び出す（Block間通信を行う）場合には、ヘッダーにセッション情報を入れてプロキシサービスを呼び出し、プロキシサービスではヘッダーからセッション情報を取得する。

しかし、適切な形式のセッション情報をヘッダーに設定した状態で外部からサービスを実行する場合において、セッションチェックを行わずにAPI実行が可能な状態となっていた。
```[tasklist]
### Tasks
- [ ] https://github.com/Personal-Data-Linkage-Module/pxr-block-proxy-service/issues/6
- [ ] https://github.com/Personal-Data-Linkage-Module/pxr-operator-service/issues/7
```

**Comment by tomo-nagae** [comment]
## 確認事項
本件の対処内容について確認させてください。
本件対処後も、現状のバッチ処理のように内部的にAPIを実行する場合は、
適切な形式のセッション情報をヘッダーに設定した状態」であれば実行可能の認識でよろしいでしょうか。

内部的にAPIを実行するような機能を新規で作成した場合、
現状と同様にセッション情報をヘッダーに設定した状態で実現できるかを確認したく、コメントさせていただきました。
例）以下のような動作を想定
* PxR-Root-Block → PxR-Root-BlockへのAPI実行
* PxR-Blockと同じ環境のPod → PxR-BlockへのAPI実行

**Comment by itoshot** [comment]
## 確認事項への回答
- 確認事項1  
Q. 現状のバッチ処理のように内部的にAPIを実行する場合は、「適切な形式のセッション情報をヘッダーに設定した状態」であれば実行可能の認識でよろしいでしょうか。  
A. 実行可能です。

- 確認事項2  
Q. 内部的にAPIを実行するような機能を新規で作成した場合、現状と同様にセッション情報をヘッダーに設定した状態で実現できるか  
A. 実現できます。本修正では、ヘッダーにセッション情報が設定されている場合、「セッション情報から通信経路を判定する処理」と「通信経路とセッション情報の組み合わせによるエラー処理」を追加しました。通信路経路判定のための正規表現は、 pxr-block-proxy-service と pxr-operator-service の config/config.jsonで設定できます。  
  - パターン1（Block間通信）：PxR-A-Block → PxR-B-Block  
  config/config.json 中の `betweenBlocks` key / value を利用します。
  - パターン2（Block内通信）：PxR-A-Block/Pod → PxR-A-Block/Pod
  config/config.json 中の `withinBlock` key / value を利用します。

- 補足事項
修正内容は、以下のプルリクエストに記載しています。
- https://github.com/Personal-Data-Linkage-Module/pxr-operator-service/pull/13
- https://github.com/Personal-Data-Linkage-Module/pxr-block-proxy-service/pull/7

**Comment by itoshot** [comment]
>

**Comment by tomo-nagae** [comment]
以下、残タスクの認識です。
https://cfj.slack.com/archives/C04GCMCFL21/p1693191384869549?thread_ts=1692262298.159939&cid=C04GCMCFL21
→マニフェストファイルの修正が必要ですが、現在この作業に着手できておりません。

**Comment by smit-akiyama** [comment]
残タスクだったmanifestファイルの修正を実施し、developブランチにマージしました。
本件は以上でクローズさせていただきます。
