### ISSUE TITLE
蓄積・共有におけるAPI実行数について

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#57]
## 確認事項
セミナー資料等で蓄積、共有のAPIを実行する際、userIdを指定して実行していますが、
自治体サービスにてPxRを利用する場合、大量のAPIを受信することになると考えています。
※例えば、10万人のユーザが存在する場合、1回蓄積するだけで、イベント蓄積とモノ蓄積で20万回APIが実行される認識です。

このような大量のAPIを実行する動作はPxRとして想定されているのでしょうか。
また、APIの実行数を減らすための方法として、
蓄積、共有APIに複数ユーザのデータを設定して実行する方法などありますでしょうか。

**Comment by r-saito-cw** [comment]
**大量のAPI実行について**
思想として、データストアそのものは接続する各サービスで行うことを想定しており、事業者間でデータを流通させて横断的な事柄に用いるのに必要なデータのみを蓄積・共有する考えがあります。

ユーザ数が増えた際の対応につきましては、実行するBlockをスケールアウトして、利用想定に合わせたパフォーマンスの拡張をしていただく想定です。

**実行数を減らす点について**
また、API 1回の実行において、１ユーザのデータ設定となります。複数ユーザのデータを設定するといった方法はございません。データの流通という点に関しては、常にリアルタイムにPxRに送信する必要性も低いと考えています。
ユースケース上許容されるのであれば、ストレージにストアされたデータを、利用頻度の少ない時間帯や定期処理で一斉に蓄積処理実行するといった処理を実装いただく、という方法が考えられます。
