### ISSUE TITLE
rootのconfigmapのファイルが足りない

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#58]
以下に配置してあるconfimapファイルですが、ファイルが足りません。
https://github.com/Personal-Data-Linkage-Module/pxr-linkage/tree/develop/delivery/manifest/eks/configmap/root

以下のファイルの配置漏れと思われます。
ctoken-ledger-service-container.yaml
identity-verificate-service-container.yaml
notification-service-container.yaml
operator-service-container.yaml
pxr-block-proxy-service-container.yaml

以下からダウンロードできるファイルがファイル数としては正しいでしょうか。
https://data-society-alliance.org/wp-content/uploads/2023/03/%E3%83%91%E3%83%BC%E3%82%BD%E3%83%8A%E3%83%AB%E3%83%87%E3%83%BC%E3%82%BF%E9%80%A3%E6%90%BA%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB_%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%89.zip

**Comment by smit-akiyama** [comment]
ファイル欠落についてご指摘ありがとうございます。
同件のプルリクエスト https://github.com/Personal-Data-Linkage-Module/pxr-linkage/pull/7 をマージいたしましたので本チケットへも完了とさせていただきます。
