### ISSUE TITLE
住民が利用開始する際の呼び出し元アクター及び権限設定について

### ISSUE THREAD

**Issue by yonaka24** [Personal-Data-Linkage-Module/pxr-linkage#66]
住民がサービスの利用を開始する手順に関して質問です。

6月29日の接続事業者向けセミナー資料を参照しております。
セミナー資料では想定ユースケースとして、A市自治体における独居高齢者の住民見守りサービスを題材に挙げていると思います。
住民がこのサービスを利用する場合、A市民IDを発行してサービス利用開始/ID連携同意をする流れになっております。
パーソナルデータ連携モジュールで該当する処理は、接続事業者向けセミナー資料のSTEP2 「サービス利用開始手続き」が該当する認識ですが、利用者の登録にあたるのは「My Condition Bookの開設」であり、これは流通制御SPのアクターがPxR Root Blockから行うという認識で正しいでしょうか。

このMy Condition Bookの開設を実行するアクターと権限について質問です。
例えば、県が基盤を構築し、基礎自治体に利用させるユースケースを考えています。
この場合、県が流通制御SPにあたる想定です。
住民ポータルは基礎自治体単位で持つことになるとすると、住民が利用開始するときには基礎自治体のアクターからMy Condition Bookの開設処理を実施すると思います。PxR Root Blockは流通制御SPの持ち物なので県のアクターでないと呼び出せない気がするのですが、このようなユースケースの場合、基礎自治体のアクターからMy Condition Book開設APIは呼び出せるのでしょうか。
直接呼び出せないのだとすると、どのようなアクター設定や権限設定をすれば実現できますか？

**Comment by itoshot** [comment]
## 質問１
#### 質問引用
> 6月29日の接続事業者向けセミナー資料を参照しております。セミナー資料では想定ユースケースとして、A市自治体における独居高齢者の住民見守りサービスを題材に挙げていると思います。住民がこのサービスを利用する場合、A市民IDを発行してサービス利用開始/ID連携同意をする流れになっております。パーソナルデータ連携モジュールで該当する処理は、接続事業者向けセミナー資料のSTEP2 「サービス利用開始手続き」が該当する認識ですが、利用者の登録にあたるのは「My Condition Bookの開設」であり、これは流通制御SPのアクターがPxR Root Blockから行うという認識で正しいでしょうか。

#### 回答
正しいです。流通制御SPの運営メンバーが PxR Root Block から「My Condition Bookの開設」 API を実行します。

## 質問２
#### 質問引用
>このMy Condition Bookの開設を実行するアクターと権限について質問です。
例えば、県が基盤を構築し、基礎自治体に利用させるユースケースを考えています。
この場合、県が流通制御SPにあたる想定です。
住民ポータルは基礎自治体単位で持つことになるとすると、住民が利用開始するときには基礎自治体のアクターからMy Condition Bookの開設処理を実施すると思います。PxR Root Blockは流通制御SPの持ち物なので県のアクターでないと呼び出せない気がするのですが、このようなユースケースの場合、基礎自治体のアクターからMy Condition Book開設APIは呼び出せるのでしょうか。直接呼び出せないのだとすると、どのようなアクター設定や権限設定をすれば実現できますか？

#### 回答
基礎自治体が流通制御SPの運営メンバーとしてのアカウントを有していない場合、基礎自治体が「My Condition Book開設」 API を直接呼び出すことはできません。

**Comment by yonaka24** [comment]
回答頂きありがとうございます。
こちらの内容で承知しました。
