### ISSUE TITLE
共有同意におけるデータの流れの方向に関する質問

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#69]
データ共有定義追加(共有同意）API{ POST/setting/share} の仕様についてご確認させてください。
 https://github.com/Personal-Data-Linkage-Module/pxr-book-manage-service/blob/bugfix/%237/openapi/book-manage_settings_share.yml
 上記のAPI概要の「個人が、アプリケーションによるデータ共有定義に対して同意し、データ共有の開始を許可します。」の詳細について確認させてください。
 
以下、
「個人」をヤマダタロウ、「アプリケーション」をアプリAとします。
アプリAによる「データ共有定義」の内容は、以下とします。
・アプリBのイベントとモノのカタログコード

この場合、「ヤマダタロウが、アプリAによるデータ共有定義に対して同意」という意味は、以下のどちらが正しいのでしょうか？
 
①アプリAが保有するヤマダタロウのデータを、アプリBにイベントおよびモノとして、渡すことに同意する。**（A→B）**
②アプリAが、アプリBの保有するヤマダタロウのイベントおよびモノを取得することに同意する。**（B→A）**
 
現在共有のシーケンスを検討しており、ご質問させていただいおります。ご確認よろしくお願いします。

**Comment by k-inoue** [comment]
下記、前提ということで回答いたします。

> 「個人」をヤマダタロウ、「アプリケーション」をアプリAとします。
> アプリAによる「データ共有定義」の内容は、以下とします。
> ・アプリBのイベントとモノのカタログコード

この場合、②として記載していただいた
「アプリAが、アプリBの保有するヤマダタロウのイベントおよびモノを取得することに同意する。」となります。

共有定義については、接続事業者向けセミナーでもご説明しておりますので、以下の資料も合わせてご確認ください。
[https://github.com/Personal-Data-Linkage-Module/pxr-linkage/tree/develop/doc/doc/セミナー/20230629_パーソナルデータ連携モジュール_セミナー資料（接続事業者様向け）/パーソナルデータ連携モジュール_セミナー資料（接続事業者様向け）.pdf](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/tree/develop/doc/doc/%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC/20230629_%E3%83%91%E3%83%BC%E3%82%BD%E3%83%8A%E3%83%AB%E3%83%87%E3%83%BC%E3%82%BF%E9%80%A3%E6%90%BA%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB_%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC%E8%B3%87%E6%96%99%EF%BC%88%E6%8E%A5%E7%B6%9A%E4%BA%8B%E6%A5%AD%E8%80%85%E6%A7%98%E5%90%91%E3%81%91%EF%BC%89/%E3%83%91%E3%83%BC%E3%82%BD%E3%83%8A%E3%83%AB%E3%83%87%E3%83%BC%E3%82%BF%E9%80%A3%E6%90%BA%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB_%E3%82%BB%E3%83%9F%E3%83%8A%E3%83%BC%E8%B3%87%E6%96%99%EF%BC%88%E6%8E%A5%E7%B6%9A%E4%BA%8B%E6%A5%AD%E8%80%85%E6%A7%98%E5%90%91%E3%81%91%EF%BC%89.pdf)
→セミナーサンプルにおける蓄積/共有の関係：スライド２４
※運動アプリの活動量のデータを見守りアプリが共有する
→共有定義の内容：スライド３１

上記内容にてCloseしてよろしければ、その旨を返信願います。
１週間経過後にお返事いただけていない場合は、CLOSEいたします。
Reopenご希望の場合は、返信いただくかコミュニティのSlackにてメンションいただけますようお願いします

**Comment by ToshinoriOchiai** [comment]
１週間以上経過しましたので、Close致します。
Close後にもReopenは可能ですので、Slack等でご連絡ください。
