### ISSUE TITLE
App-Blockへのログインの競合回避方法について　※回答希望日：11/10

### ISSUE THREAD

**Issue by yoshi-sakagami** [Personal-Data-Linkage-Module/pxr-linkage#72]
**※11/9のPxRコミュニティ定例で質問した内容となります。**

まず、連携、蓄積等の処理の順序(API呼び出し順序）は以下と認識しています。
1. App-Blockへのログイン（/operator/operator/login）→sessionId(operator_type2_session）、_csrf、XSRF-TOKENの3つのハッシュ値がset-cookieされる。
1. 後段のAPI（連携URL発行、利用者ID取得、等）の呼び出し。その際、1.で払い出されたsessionId, _csrf, XSRF-TOKENをCookie、HTTPヘッダに指定する。

1.で払い出される3つのハッシュ値はApp-Blockへのログインの度に更新されるとのことで、競合が発生し1.と2.の間に別のApp-Blockのログインが入り込むと、先発の2.のAPI実行がエラーになると思います。  

これを回避する方法についてご教授ください。実績あるやり方があればそれが望ましいです。
  
11/9のPxRコミュニティ定例において、この事象は既知であり、且つ以前議論になっており、その時議論した記録（issue？）が残っており、その内容を記載したURLをいただけるとのことでした。

なお、こちらの都合で申し訳ないのですが、本件かなり急いでおりまして、**明日（11/10）中** にいただきたいです。  
自治体様向けの開発を実施している中、アプリ事業者・基盤を開発する各開発会社間のインタフェースにおいて喫緊の課題となっており、ご協力をお願いいたします。

URLの共有だけなのでこのくらいの期間で回答可能と考えておりますが、もし難しい場合は回答可能な日時についてご回答いただければと思います。

**Comment by r-saito-cw** [comment]
本件において、途中で同一IDにてログインがあった場合にはお問い合わせ内容に記載いただいた動きのとおりとなります。
現状においてAPIにてこれを回避する設定などはございません。
同一IDで別のログインが入り込まないよう、ユーザインタフェース部分などAPI以外の部分にてガードをするといった方法で対応頂きたく存じます。

API自体でガードする仕組みについて、改善要望としてIssue発行いただけたらと存じます。


上記内容にてCloseしてよろしければ、その旨を返信願います。
１週間経過後にお返事いただけていない場合は、CLOSEいたします。
Reopenご希望の場合は、返信いただくかコミュニティのSlackにてメンションいただけますようお願いします。

**Comment by r-saito-cw** [comment]
1週間経過しましたのでCLOSEします。
