### ISSUE TITLE
利用規約更新後に未同意規約取得APIを実行してもデータが取得できない

### ISSUE THREAD

**Issue by k-inoue** [Personal-Data-Linkage-Module/pxr-linkage#75]
未同意規約取得（個人）APIを実行したのですが、値がnullで返却されます。

> {"termsOfUse":{"platform":null,"region":null},"store":null,"share":null}

★試した内容
①個人ログイン
②利用規約更新：PUT /catalog-update/platform-terms-of-use
③Region改定再同意依頼バッチ実行（PxR-Root-Block）
④未同意規約取得（個人） ：GET /term_of_use/request/list
⑤利用規約同意：POST /ind/?block=$pxr-root-block&path=%2Fbook-manage%2Find%2Fterm_of_use%2Fplatform'

★結果
未同意規約取得APIを実行すると値がnullとなり、以下の結果が返却される
{"termsOfUse":{"platform":null,"region":null},"store":null,"share":null}

**Comment by smit-akiyama** [comment]
本件は #52 と同件で、追加の操作が必要です。
詳細については上記のIssueを参照ください。
本件はクローズさせていただきます。
