### ISSUE TITLE
PxRの各APIは並列実行可能かどうか

### ISSUE THREAD

**Issue by yoshi-sakagami** [Personal-Data-Linkage-Module/pxr-linkage#77]
PxRの下記それぞれのAPIについて、異なるリクエストパラメータで同時刻に並列処理することは可能でしょうか。
★本質問事項が最優先で、Noの場合は一番下の追加質問にも併せてご回答いただけますと幸いです。
 
①利用者一覧検索API /book-operate/user/list
②イベント蓄積API　 /book-operate/event/{userId}
③モノ追加API　　　 /book-operate/thing/{userId}/{eventId}
④データ共有定義取得API　/book-operate/setting/share/{userId}/{applicationCatalogCode}
⑤データ共有によるデータ取得API /book-operate/share
 
イメージ) PxRにて下記APIリクエスト1,2を同時刻に受信した場合、並列(00:00:00～00:00:01)に実行されるのか
　 　　　 1.ユーザA、データBのイベント蓄積API (受信時刻：00:00:00、処理時間00:00:00～00:00:01)
   　　　 2.ユーザB、データBのイベント蓄積API (受信時刻：00:00:00、処理時間00:00:00～00:00:01)
 
 
上記動作について弊社側でも検証を行っており、一部APIでは並列処理が可能な個所が見えております。
 
■並列処理不可に見えるAPI
・検証概要
　　蓄積関連のAPIが並列処理可能か検証
・検証内容
　　API②③(ユーザA)を1並列(中の②③は直列)とし、同時刻に100～500並列でPxRにAPIを叩いた際の時間を計測
　　※↑のイメージでユーザを100人分並列で叩くイメージ
・検証条件
　　ユーザ数：100～500
　　データ数：1ユーザ当たり5種類のイベント
　　測定環境：
　　  APIサーバ Pod数：6
　  　PostgreSQL：2コアvcpu, 4GiBメモリ、120IOPSストレージ
・測定結果
　　100ユーザ：44秒
　　200ユーザ：85秒
　　300ユーザ：120秒
　　500ユーザ：220秒
 
　並列数に限らず★一次関数的に処理時間が伸びる★結果となった。
　参考として、Pod数を上げる、DBサーバの性能を上げるなど検討したが、処理改善は見られない
　PostgreSQLサーバ上の最大コネクション数は300弱で、MAXCONNECTION設定は1000のため影響なしと思われる
 
■並列処理可に見えるAPI
・検証概要
　　利用者一覧検索APIが並列処理可能か検証
・検証内容
　　API①を1並列とし、同時刻に1,100並列でPxRにAPIを叩いた際の時間を計測
・検証条件
　　ユーザ数：1、100
　　測定環境：
　　  APIサーバ Pod数：6
　　  PostgreSQL：2コアvcpu, 4GiBメモリ、120IOPSストレージ
・測定結果
　　1ユーザ：0.7秒
　　100ユーザ：1秒
 
　並列数を上げても処理時間が変わらない結果となった。
 
 
■上記がNoである場合の追加質問
・以前、質問の回答でNEC社様の環境で運用実績はあるとのことでしたが、
　その環境での処理性能と上記モデルでの処理性能を見比べた際に、
　リニアにはならないはず・もっと処理性能は出るはずなどといった違和感があればコメントいただけると助かります。
 
・Pod数を増やしても速くならない、DBの負荷が変わらない点が気になっております。
　弊社でも調査を進めておりますが、処理時間改善のためのPxRのコンフィグがあればご教示いただけますと幸いです。
 
・アプリ・基盤側で処理を高速化するために対応可能な対処はありますでしょうか。

**Comment by r-saito-cw** [comment]
@yoshi-sakagami 
質問および検証結果の投稿ありがとうございます。

ユーザの環境での性能の質問回答として技術支援を必要とする際は、別途、弊社へご連絡願います。弊社との契約という形で技術支援は可能です。弊社からGitHubで提供できる情報に限りがあるのに加え、作動条件も異なると思います。
 
そのうえでこの件は、まず処理全体のボトルネックがどこにあるのか計測するのが良いと思います。
例えば、root-Blockは多数ユーザの処理時にボトルネックになり得る部分です。Podの数が６とあるのですが、どのBlockにいくつPodがあり、さらにそのPodのなかで稼働しているサービス（コンテナ）のCPUやメモリの使用率がどのような状況かを確認するのが良いと思います。

**Comment by r-saito-cw** [comment]
一週間経過したため、CLOSEします。
