### ISSUE TITLE
CloudSearchを使用するAPIの実行フロー

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#79]
CloudSearchを利用するサービスについて調査しておりますが、
catalogサービス（pxr-catalog-service）で使用している認識です。
CloudSearchが使用されるAPIは以下と思われますが、認識あっておりますでしょうか。
また、実際の運用上どのようなケースで呼ばれますでしょうか。

■SearchService_Stub.ts：getRecord()が呼ばれるAPI
・カタログ全文検索（POST /catalog/text）
　→UT内にしか見当たらない
※カタログ検索系のAPIではCloudSearchは使用していない理解でよろしいでしょうか。

■SearchService_Stub.ts：updateRecord()が呼ばれるAPI
・カタログ追加（POST /catalog/model）
・カタログ更新（PUT /catalog/model/:code）
・変更セット更新（POST /catalog/updateSet/approval/:id）
・変更セット申請（POST /catalog/updateSet/request）

■SearchService_Stub.ts：deleteRecord()が呼ばれるAPI
・カタログ削除（DELETE /catalog/model/:code）
・変更セット更新（POST /catalog/updateSet/approval/:id）
・変更セット申請（POST /catalog/updateSet/request）

**Comment by smit-akiyama** [comment]
CloudSearchはカタログ項目からキーワード検索するときの全文検索機能として使用することを想定しています。
全文検索対象として想定する項目は、カタログ項目のnameとdescriptionです。
OSS版としてはスタブ化していますので、必要に応じて事業者様側で実装をお願いいたします。

**Comment by smit-akiyama** [comment]
CloudSearchについての注釈をアプリケーション開発ガイドに記載いたしました。
QAへの回答から１週間以上経過しましたので、Close致します。
Close後にもReopenは可能ですので、Slack等でご連絡ください
