### ISSUE TITLE
log4js及びclass-validatorのライブラリバージョンアップに伴ってmanifestファイルの設定変更が必要

### ISSUE THREAD

**Issue by kentaro000** [Personal-Data-Linkage-Module/pxr-linkage#80]
# 概要
以下のプルリクエストで対応しているライブラリバージョンアップに伴い、manifestファイルの修正が必要となる。
　・https://github.com/Personal-Data-Linkage-Module/pxr-block-proxy-service/pull/9
　・https://github.com/Personal-Data-Linkage-Module/pxr-binary-manage-service/pull/6
　・https://github.com/Personal-Data-Linkage-Module/pxr-book-operate-service/pull/12
　・https://github.com/Personal-Data-Linkage-Module/pxr-catalog-update-service/pull/9
　・https://github.com/Personal-Data-Linkage-Module/pxr-certificate-manage-service/pull/7
　・https://github.com/Personal-Data-Linkage-Module/pxr-local-ctoken-service/pull/6
　・https://github.com/Personal-Data-Linkage-Module/pxr-notification-service/pull/7
　・https://github.com/Personal-Data-Linkage-Module/pxr-catalog-service/pull/8
　・https://github.com/Personal-Data-Linkage-Module/pxr-access-control-service/pull/7
　・https://github.com/Personal-Data-Linkage-Module/pxr-identity-verificate-service/pull/8
　・https://github.com/Personal-Data-Linkage-Module/pxr-certification-authority-service/pull/9
　・https://github.com/Personal-Data-Linkage-Module/pxr-access-control-manage-service/pull/10
　・https://github.com/Personal-Data-Linkage-Module/pxr-book-manage-service/pull/10
 　・https://github.com/Personal-Data-Linkage-Module/pxr-operator-service/pull/19
　・https://github.com/Personal-Data-Linkage-Module/pxr-ctoken-ledger-service/pull/8　

## 変更点①
・log4jsのライブラリバージョンアップに伴い、以下の設定ファイルのプロパティを変更
　- log4js.config.json
　　- daysToKeep ⇒ numBackups

## 変更点②
・class-validatorのライブラリバージョンアップに伴い、以下の設定ファイルのプロパティ名を変更
　- message.json
　　-  isUUID ⇒ isUuid
　　-  length ⇒ isLength

**Comment by smit-akiyama** [comment]
本件は以下プルリクにて対応しましたのでクローズいたします。
https://github.com/Personal-Data-Linkage-Module/pxr-linkage/pull/73
