### ISSUE TITLE
ユーザが多い状態だと、create-user-batchが正常に動作しない

### ISSUE THREAD

**Issue by jou-imaizumi** [Personal-Data-Linkage-Module/pxr-linkage#89]
## 事象
性能の検証用に10000人程のユーザを作成し、検証を行っています。
create-user-batchを15分に一度実行しながら、10000人のユーザのbook開設を行いました。
その結果、7000人のユーザを作成したあたりから、create-user-batchでエラーになってしまい。連携ができませんでした。
登録しているユーザが多い状態だと、create-user-batch内部の処理(my-Condition-Book取得)の箇所でエラーになるようでした。
以下に詳細を記載するので、ご確認よろしくお願いします。

## create-user-batchのログ
[create-user-batch.log](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/14173998/create-user-batch.log)
[app1_book-operate-application.log](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/14173996/app1_book-operate-applicationLog.log)
[app1_book-operate-http.log](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/14173997/app1_book-operate-httpLog.log)
[app1_book-operate-access.log](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/14173999/app1_book-operate-accessLog.log)

#### 実行コマンド
```
curl -v -k -X POST \
'https://<rootドメイン>/pxr-block-proxy/pxr-block-proxy/?path=%2Fbook-manage%2Fsearch' \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
-H 'x-xsrf-token:fGfBixEQ-juhj6LaoM-y86v2iRyVqnHM6S2Q' \
-b 'operator_type3_session=045c763488d7d180baca7ebb698f5a0a269c907b7165559ef489a676511caf8d;_csrf=EtQ6vrzrQr9OBuzmsuodDDAk' \
  -d'{"pxrId":null,"createdAt":null,"offset":5,"limit":1}'
```

#### レスポンス
```
[{"pxrId":"test_user5","status":0,"attributes":{},"cooperation":[{"actor":{"_value":1000785,"_ver":2},"region":{"_value":1000790,"_ver":5},"app":null,"wf":null,"userId":"308e385a-7705-42c1-9a2f-5b88f6e9d575","startAt":"2024-02-02T21:15:04.002+0900","status":1},{"actor":{"_value":1000787,"_ver":2},"region":null,"app":{"_value":1000800,"_ver":3},"wf":null,"userId":"test_user5app1","startAt":"2024-02-02T21:14:59.960+0900","status":1},{"actor":{"_value":1000802,"_ver":2},"region":null,"app":{"_value":1000810,"_ver":3},"wf":null,"userId":"test_user5app2","startAt":"2024-02-02T21:15:00.951+0900","status":1},{"actor":{"_value":1000812,"_ver":2},"region":null,"app":{"_value":1000829,"_ver":3},"wf":null,"userId":"test_user5app3","startAt":"2024-02-02T21:15:02.082+0900","status":1}],"userInformation":{"_code":{"_value":1000373,"_ver":1},"item-group":[{"title":"氏名","item":[{"title":"姓","type":{"_value":30019,"_ver":1},"content":" サンプル"},{"title":"名","type":{"_value":30020,"_ver":1},"content":"太郎"}]},{"title":"性別","item":[{"title":"性別","type":{"_value":30021,"_ver":1},"content":"男"}]},{"title":"生年（西暦）","item":[{"title":"生年（西暦）","type":{"_value":1000372,"_ver":1},"content":2000}]},{"title":"住所（行政区）","item":[{"title":"住所（行政区）","type":{"_value":1000371,"_ver":1},"content":"東京都港区"}]},{"title":"連絡先電話番号","item":[{"title":"連絡先電話番号","type":{"_value":30036,"_ver":1},"content":"080-0000-0000","changable-flag":true,"require-sms-verification":false}]}]}}]
```

#### 実行コマンド
```
curl -v -k -X POST \
'https://<rootのドメイン名>/pxr-block-proxy/pxr-block-proxy/?path=%2Fbook-manage%2Fsearch' \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
-H 'x-xsrf-token:fGfBixEQ-juhj6LaoM-y86v2iRyVqnHM6S2Q' \
-b 'operator_type3_session=045c763488d7d180baca7ebb698f5a0a269c907b7165559ef489a676511caf8d;_csrf=EtQ6vrzrQr9OBuzmsuodDDAk' \
  -d'{"pxrId":null,"createdAt":null}'
```

#### レスポンス
```
{"status":500,"message":"宛先ブロックのリバースプロキシーAPIの呼び出しに失敗しました"}
```

#### ログ

[root_book-manage-access.log](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/14174937/root_book-manage-access.log)
[root_book-manage-http.log](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/14174938/root_book-manage-http.log)
[root_pxr-block-proxy-access.log](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/14174939/root_pxr-block-proxy-access.log)
[root_pxr-block-proxy-application.log](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/14174940/root_pxr-block-proxy-application.log)
[root_pxr-block-proxy-http.log](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/files/14174941/root_pxr-block-proxy-http.log)

**Comment by yoshi-sakagami** [comment]
ユーザ数が多くエラーになっているときの環境情報について共有しておきます。
（特段負荷がかかりすぎて落ちている印象はない）

■テスト環境情報（Azure）
DBスペック：Azureフレキシブルサーバ　Standard_D2ds v4（2コア　8GiBメモリ）
ノードプールのスペック：Standard D4s v3 （4vpc、16GiBメモリ）　
■エラー時のメトリック
・DB
![DBメトリック](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/141890430/0da42ae6-dbb2-4879-94f3-8bc14c96412f)
・ノード
![ノード負荷](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/141890430/02e17521-3df0-4b9e-b6b4-79c206c1cd48)
・コンテナごとのCPU、メモリ使用率（エラー発生時）
![コンテナごとのCPU、メモリ使用率](https://github.com/Personal-Data-Linkage-Module/pxr-linkage/assets/141890430/7a27b276-3fda-41ec-95cc-5a63b63759a1)

**Comment by smit-akiyama** [comment]
情報提供ありがとうございました。

ログを確認すると、book-manage-serviceのMy-Condition-Book一覧取得APIでリクエストは受け取っているが、その後の処理を確認できないため、途中で異常終了していると推測しています。
create-user-batch が呼び出している 利用者作成(バッチ)API (POST book-operate/user/batch) が My-Condition-Book一覧取得API (POST book-manage/search) を実行する処理を、offset/limitを利用したforループへ変更して分割取得するように変更することで事象解決を図ります。

### 修正概要
- 利用シーン
  - Book開設済みのユーザーについて、利用者ID連携済みのブロックのユーザーを作成する
- 利用オペレーター
  - アプリケーション（バッチ）
- 修正方針
  - 利用者作成バッチ内でBook管理サービス.Book一覧取得（/book-manage/search）の呼び出しを追加し、1000件単位で取得する（ループ処理）
  - Book運用サービス.利用者作成（バッチ）APIのリクエストを、PXR-IDを配列で受け取るように修正し、処理対象とする

#### 利用者作成バッチ create-user-batch
- 修正内容
  - Book運用サービス.利用者作成（バッチ）APIをループ処理内で呼ぶように修正
  - ループ処理内でBook管理サービス.Book一覧取得APIの呼び出しを追加し、取得結果からPXR-IDの配列オブジェクトを作成する
    - offset初期値：0、limit：1000
  - Book運用サービス.利用者作成（バッチ）APIのリクエストにPXR-IDの配列を追加
  - Book管理サービス.Book一覧取得APIの取得件数がlimit未満で処理終了

#### Book運用サービス.利用者作成（バッチ）API POST: /book-operate/user/batch
- 修正内容
  - リクエストでPXR-IDの配列を受け取るように修正
  - リクエストで受け取ったPXR-IDをBook管理サービス.Book一覧取得APIのリクエストに設定して、取得件数を限定する

### 横展開（Book管理サービス.Book一覧取得API呼び出し箇所）
#### CToken台帳サービス.Local-CToken差分登録API POST: /ctoken-ledger/local
- 利用シーン
  - Local-CTokenの差分情報をCToken台帳に登録する
- 利用オペレーター
  - アプリケーション（バッチ）
- 修正方針
  - cmatrixの利用者ID、アクター、APPの情報からPXR-IDを特定する際に、Book管理サービス.Book一覧取得API(POST:/book-manage/search)を呼び出しMy-Condition-Bookを全件取得している箇所を、cmatrixごとにユーザー取得API(POST:/book-manage/search/user)を呼び出すように変更する
- 修正内容
  - Book管理サービス.Book一覧取得API(POST:/book-manage/search)の呼び出しを削除
  - cmatrix配列のループ処理の中で、cmatrixのuserId、アクター、APPを元に、Book管理サービス.ユーザー取得API(POST:/book-manage/search/user)を呼び出し、PXR-IDを取得する
