### ISSUE TITLE
自アプリで蓄積したデータを自アプリで共有できるか

### ISSUE THREAD

**Issue by tomo-nagae** [Personal-Data-Linkage-Module/pxr-linkage#90]
## 質問事項
アプリAシステムにて蓄積したデータを、アプリAシステムで共有APIを利用しデータ取得できるか
問い合わせを受けており実現可能であるか確認させてください。

検証できていない中での質問となり、大変申し訳有りませんが
内容の確認をお願いいたします。

以下について実現可能であるかを確認
1. アプリAの共有定義としてアプリAで蓄積するデータの定義を作成する
1. アプリAシステムにてPxRに蓄積したパーソナルデータを共有APIを使用してデータ取得する 

また、他に実現できる方法はありますでしょうか。

**Comment by smit-akiyama** [comment]
ご質問に回答します。

> 1. アプリAの共有定義としてアプリAで蓄積するデータの定義を作成する

カタログ定義としては以下のような構成と理解しました。
（イメージ）
app-block-A
　└app-A
　　├蓄積定義-A
　　│　└データ種-A
　　└共有定義-A
　　　　└データ種-A

> 2. アプリAシステムにてPxRに蓄積したパーソナルデータを共有APIを使用してデータ取得する

上記カタログ構成で
　app-Aにデータ種-Aを蓄積したあと
　app-Aでデータ種-Aに対する共有APIを実行することで
　app-A自身にデータ種-Aを共有可能か
という質問と理解しました。
 
以上の理解を前提として回答いたします。
上記手順にて自アプリによる共有は可能ですが、本モジュールのコンセプトとは異なります。
本モジュールにおける蓄積とは、APPプロバイダが、自身が管理する利用者のパーソナルデータの一部を、別APPプロバイダが個人同意に基づいて利用可能（共有）な状態にすることです。
ですので自アプリで蓄積したデータを自アプリで使うという目的のみの場合では、本モジュールを使う必要が薄いかと思います。

本件に関して、追加でのご確認等があればご返信お願いいたします。
ご返信がないまま1週間経過しましたら、Closeさせていただきます。
Close後にもReopenは可能ですので、Slack等でご連絡ください。

**Comment by smit-akiyama** [comment]
１週間経ちましたのでcloseいたします。
